### ISSUE TITLE
Can't install on Debian

### ISSUE THREAD

**Issue by AbstractUmbra** [libgit2/pygit2#1007]
User: root
libgit2: 1.0.0, installed from source
ldconfig output:-
```shell
# ldconfig -p  | grep libgit
        libgit2.so.1.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgit2.so.1.0
        libgit2.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgit2.so
```

When installing pygit2 from pip (`python3.7 -m pip install -U pygit2`) it is failing to install with the attached error log.
[pygit2error.txt](https://github.com/libgit2/pygit2/files/4606595/pygit2error.txt)

**Comment by jdavid** [comment]
The error message says it:

> You need a compatible libgit2 version (1.0.x)

It's not picking the right libgit2.

My advice is to use the binary wheels, which include libgit2.
