### ISSUE TITLE
gitattributes are supported but not documented

### ISSUE THREAD

**Issue by aspiers** [libgit2/pygit2#1017]
I see that `pygit2.Repository.get_attr()` was added 5 years ago by 74b81bf18076 to allow retrieval of attributes, and it's still there:

https://github.com/libgit2/pygit2/blob/fb083cc3314c4f60a4c4e950fdb31a4b8f4960db/pygit2/repository.py#L1218-L1223

but it is not mentioned anywhere in the docs.

**Comment by keszybz** [comment]
FWIW, I just added a use of `.get_attr()` in a new project and it works nicely. Just the docs are missing.

**Comment by jdavid** [comment]
This is an easy pick for anyone willing to make a PR

**Comment by keszybz** [comment]
https://github.com/libgit2/pygit2/pull/1105 adds a bit more.
