### ISSUE TITLE
No module named 'pygit2._pygit2

### ISSUE THREAD

**Issue by L11KAS** [libgit2/pygit2#1020]
When importing pygit2 library in aws lambda, I get the following errors for different runtime:

`Python 2.7 - Unable to import module 'github_pull_source': No module named _pygit2
Python 3.6 - Unable to import module 'github_pull_source': /var/task/_cffi_backend.so: undefined symbol: _Py_ZeroStruct
Python 3.7 - Unable to import module 'github_pull_source': No module named 'pygit2._pygit2'
Python 3.8 - Unable to import module 'github_pull_source': No module named 'pygit2._pygit2'

My imports are as follow: 
from pygit2 import Keypair, discover_repository, Repository, clone_repository, RemoteCallbacks`

Please help. 

Thanks.

**Comment by omniproc** [comment]
from the error it looks like you never installed pygit2?

**Comment by L11KAS** [comment]
Hi @omniproc  and thanks for your response.

I have now managed to solve the problem by creating a lambda layer. The problem seems to be with the python packages that are in the lambda container by default. See details in this issue I raised here: https://github.com/JayDoubleu/aws-lambda-layer-pygit2-ed25519/issues/1

Hopefully that will help other too.
