### ISSUE TITLE
pip install pygit2 on MacOS does not provide GIT_FEATURE_SSH

### ISSUE THREAD

**Issue by jsjohnst** [libgit2/pygit2#1024]
On a fresh install of macOS Catalina (10.15.6), installing `pygit2` via the following steps does not include SSH support by default:

```shell
$ brew install python libgit2
$ pip3 install pygit2
```

When you do step 2 above, the output is as follows:

```
Collecting pygit2
  Downloading pygit2-1.2.1-cp38-cp38-macosx_10_9_x86_64.whl (808 kB)
     |████████████████████████████████| 808 kB 3.7 MB/s
Collecting cached-property
  Downloading cached_property-1.5.1-py2.py3-none-any.whl (6.0 kB)
Collecting cffi>=1.4.0
  Downloading cffi-1.14.1-cp38-cp38-macosx_10_9_x86_64.whl (176 kB)
     |████████████████████████████████| 176 kB 71.9 MB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 65.8 MB/s
Installing collected packages: cached-property, pycparser, cffi, pygit2
Successfully installed cached-property-1.5.1 cffi-1.14.1 pycparser-2.20 pygit2-1.2.1
```

As you can see, the _"There are not binary wheels available for OS X, so you will need to install the source package."_ mentioned in the [Installation](https://www.pygit2.org/install.html#installing-on-os-x) part of the docs is currently wrong.

The bigger problem is that when you fire up a Python console and check the supported features, you find:

```shell
>>> import pygit2
>>> pygit2.features
11
>>> bool(pygit2.features & pygit2.GIT_FEATURE_SSH)
False
```

Which obviously will lead to the following error when you try to clone a repository using SSH transport:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pygit2.clone_repository("ssh://git@git-server-name:1234/repo.git", "/tmp/repo", callbacks=pygit2_rcb)
  File "/usr/local/lib/python3.8/site-packages/pygit2/__init__.py", line 214, in clone_repository
    payload.check_error(err)
  File "/usr/local/lib/python3.8/site-packages/pygit2/callbacks.py", line 93, in check_error
    check_error(error_code)
  File "/usr/local/lib/python3.8/site-packages/pygit2/errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: unsupported URL protocol
```

The solution I found was to uninstall pygit2 and reinstall via:

```shell
$ pip3 install pygit2 --no-binary pygit2
```

which forces a build and thus detects `libssh2` and `libgit2` being properly installed.

Running a Python console, we then find:

```shell
>>> import pygit2
>>> pygit2.features
15
>>> bool(pygit2.features & pygit2.GIT_FEATURE_SSH)
True
```

and all is well with pygit2 afterwards.

I'd suggest updating the docs at minimum, but hopefully there is a way to actually fix this from being an issue on macOS.

**Comment by webknjaz** [comment]
> ```shell
> $ brew install python libgit2
> ```

When installing from wheels, pygit2 will always use a bundled libgit2 shared library. You can only make it link against your system lib by installing from source which I see you've figured out already.

I think sending a PR updating docs is welcome.

If you want to talckle adding support to macOS wheels, here's some pointers:
* These wheels are built on GHA. The workflow has SSH flag clearly disabled @ https://github.com/libgit2/pygit2/blob/c20cce8/.github/workflows/macos.yml#L81. So first thing to do is to flip `USE_SSH` there
* And here's a script that builds manylinux wheels. You'll likely need to throw a statically compiled libssh2 into the soup like I did here: https://github.com/libgit2/pygit2/blob/c20cce8/travis/build-manylinux-wheels.sh#L43-L147.


cc @rcoup @jdavid

**Comment by rcoup** [comment]
Not building libgit2 with libssh2 was a deliberate decision at the time: [libssh2 is deprecated in Redhat 7 removed in 8](https://github.com/libgit2/libgit2/issues/5225) (similarly centos/etc), and libgit2 doesn't have libssh support yet

See the discussion in https://github.com/libgit2/pygit2/issues/994#issuecomment-617049941

**Comment by webknjaz** [comment]
Oh, fair enough. I'm also having to deal with libssh lately for similar reasons (https://github.com/ansible/pylibssh).

OTOH bundling it would be the quickest solution. Even if the project migrates over to libssh, until that happens it probably makes sense to use what's supported...

**Comment by cutec-chris** [comment]
Its for me the same on windows, how can i add ssh support ? is it only add libssh2 or do i have to rebuild libgit2 ?

**Comment by jdavid** [comment]
Rebuild libgit2. On Linux it's very easy with `build.sh`, on macOS should be easy as well, no idea about Windows (look libgit2's documentation).

**Comment by cutec-chris** [comment]
in linux it seems to work, i dont need macos, and general it should be done with pip install. in git itself this works and its an basic feature of git

**Comment by cutec-chris** [comment]
Python is the number one programming language on most indexes
> A portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API.
so solid api on core git methods means to me that basic git features should work out of the box :)

**Comment by jdavid** [comment]
I'll review a PR, when there's one. Closing this. There's really no point to open an issue asking for a feature. Features should be in the form of PRs.

**Comment by jsjohnst** [comment]
@jdavid I opened a detailed issue clearly describing broken functionality, not asking for features. I've since been busy trying to improve the performance of pygit2's blame functionality and not circled back to this as the issue filed here provides everything one needed to work around the broken functionality in the mean time. This tone/attitude of yours is very demotivating though and makes me reconsider doing anything with this project.
