### ISSUE TITLE
aarch64 wheels on pypi

### ISSUE THREAD

**Issue by bryceml** [libgit2/pygit2#1042]
Manylinux2014 got released with support for wider selection of architectures: aarch64, arm32, ppc64le, s390x. Are there plans to use it for releasing wheels on pypi for other architectures than x86-64/i686?

I'm particularly interested in aarch64 wheels as it makes installing newer versions of pygit2 much easier on ubuntu 20.04 since the version of libgit2-dev they have in the repo is too old to build newer versions of pygit2.

**Comment by jdavid** [comment]
I've added arm64 to Travis so now it's tested, but for upgrading to 2014 I'll wait a PR.

**Comment by jdavid** [comment]
Not yet released, but we now generate the wheels for aarch64.
Please test the wheels here, https://github.com/libgit2/pygit2/actions/runs/856445474

**Comment by jdavid** [comment]
Released
