### ISSUE TITLE
Equivalent of 'git diff ... -- paths'

### ISSUE THREAD

**Issue by jaanauati** [libgit2/pygit2#1049]
This may be a dumb question, but not clear for me, what's the equivalent of `git diff ... -- foo.txt `?.

Thank you!

**Comment by zomglings** [comment]
@jaanauati : The way I do this with pygit2 is to navigate the [`Diff`](https://www.pygit2.org/diff.html#the-diff-type) object returned by `Repository.diff` to get the hunks only for that file.

**Comment by jaanauati** [comment]
@zomglings I ended up doing it in that way. Thank you!.
