### ISSUE TITLE
A new version please? (1.6.0 or something)

### ISSUE THREAD

**Issue by feisuzhu** [libgit2/pygit2#1069]
We are expecting the proxy feature and it seems landed on master (https://github.com/libgit2/pygit2/pull/1063).
We have been waiting for a long time.

**Comment by jdavid** [comment]
Can you test the wheels https://github.com/libgit2/pygit2/actions/runs/711340943 ?

**Comment by feisuzhu** [comment]
![2021-04-06-162103_1097x487_scrot](https://user-images.githubusercontent.com/857880/113681149-3a588b00-96f4-11eb-83ab-a40902eeed63.png)

Probably not……

**Comment by feisuzhu** [comment]
Additionally, after fixing the offending line

```python
proxy_opts.url = ffi.new('char[]', to_bytes(proxy))
```

things become weird

![2021-04-06-175038_1265x721_scrot](https://user-images.githubusercontent.com/857880/113692946-a6d98700-9700-11eb-896b-11111c5085f8.png)

It's not 100% reproducible, but definitely would show up after times.

**Comment by jdavid** [comment]
Do you think you could make a PR with a unit test showing the error?

**Comment by jdavid** [comment]
ping @sathieu

**Comment by sathieu** [comment]
I'm just using the AUTO mode (`proxy=True`) together with https://github.com/libgit2/libgit2/pull/5796, this works perfectly. Need to dig in ffi to understand the problem.

**Comment by sathieu** [comment]
@feisuzhu Have you tried:
```python
proxy_opts.url = ffi.string(proxy)
```

Ref: https://cffi.readthedocs.io/en/latest/ref.html#ffi-string-ffi-unpack

**Comment by sathieu** [comment]
> 
> 
> @feisuzhu Have you tried:
> 
> ```python
> proxy_opts.url = ffi.string(proxy)
> ```
> 
> Ref: https://cffi.readthedocs.io/en/latest/ref.html#ffi-string-ffi-unpack

No, no, no. Sorry for the noise ...

**Comment by feisuzhu** [comment]
> I'm just using the AUTO mode (`proxy=True`) together with [libgit2/libgit2#5796](https://github.com/libgit2/libgit2/pull/5796), this works perfectly. Need to dig in ffi to understand the problem.

Can confirm, I end up using `proxy=True` too.

**Comment by sathieu** [comment]
@feisuzhu Have you tried:

```python
proxy_opts.url = ffi.new('char[]', proxy)
```

ffi has a doc about [memory ownership](https://cffi.readthedocs.io/en/latest/using.html#working-with-pointers-structures-and-arrays).

Otherwise @jdavid, maybe we should drop support for `proxy=url`?

**Comment by feisuzhu** [comment]
> @feisuzhu Have you tried:
> 
> ```python
> proxy_opts.url = ffi.new('char[]', proxy)
> ```
> 
> ffi has a doc about [memory ownership](https://cffi.readthedocs.io/en/latest/using.html#working-with-pointers-structures-and-arrays).
> 
> Otherwise @jdavid, maybe we should drop support for `proxy=url`?

IMHO `ffi.new('char[]', to_bytes(proxy))` returns an owned reference(`to_bytes` returns Python `bytes`, not another `cdata`), so the problem lies elsewhere.

I'll try again though.

**Comment by sathieu** [comment]
@feisuzhu Yes but the result of `to_bytes(proxy)` is released as soon a this line is done.

**Comment by feisuzhu** [comment]
@sathieu 

Did some experiment, found that it's `ffi.new('char[]', xxx)` should be kept referenced, not the `bytes`.
If I keep the `char[]` referenced in global the issue disappears.

**Comment by jdavid** [comment]
Pushed a commit. Can you try with the wheels at https://github.com/libgit2/pygit2/actions/runs/774665500#artifacts ?
