### ISSUE TITLE
Issue with Release 1.7.0 on Windows

### ISSUE THREAD

**Issue by petrSchreiber** [libgit2/pygit2#1094]
Dear @jdavid,

thank you for your continuous work on pygit2 module.

Sadly, in the latest release - 1.7.0 - I can observe error I did not see previously:
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Could it be a missing wheel or some similar issue?

Petr

**Comment by jdavid** [comment]
It looks like pip picked up the source package. Check the Python version, in these release there are windows binary wheels for 3.7, 3.8 and 3.9

If you have one of these versions then try again, I see you opened the issue 39 minutes ago, the wheels were not fully uploaded at that time.
