### ISSUE TITLE
SSL issues with compiled version 1.7.2

### ISSUE THREAD

**Issue by wlozano0collabora** [libgit2/pygit2#1115]
When using compiled version 1.7. 2 on Debian Bullseye through 

```
pip3 install pygit2
```

I observe that certificate from gitlab.apertis.org fails with 

```
_pygit2.GitError: user rejected certificate for gitlab.apertis.org
```

However this issue is not reproduced on version `pygit2 version 1.7.1` or with `pygit2 version 1.7.2 with libgit2 1.3.0 compiled from sources`.

**Comment by 4a6f656c** [comment]
This is almost certainly due to the bundling of OpenSSL 1.0.2k (https://github.com/libgit2/pygit2/issues/1136#issuecomment-1087645337, https://github.com/libgit2/pygit2/issues/1136#issuecomment-1223786378).

**Comment by jdavid** [comment]
Try with the latest release v1.11.1 which includes openssl 1.1
Reopen if it does not work with v1.11.1
