### ISSUE TITLE
Use default user if author/committer is None

### ISSUE THREAD

**Issue by pypingou** [libgit2/pygit2#113]
To make a commit one as to precise an author and a committer, these argument cannot be null (None), but if they are (None) could git used the information set at the system level in ~/.gitconfig?

It would be nice to see libgit2/pygit2 support this.

**Comment by tmr232** [comment]
If we don't want to support it, maybe close the issue?
@carlosmn @jdavid

**Comment by MiroslavMikus** [comment]
@carlosmn Is the 'default_signature' in the libgit2sharp library as well??
