### ISSUE TITLE
Shared Library Version Mismatch Issues with Wheel on Debian 11

### ISSUE THREAD

**Issue by DaAwesomeP** [libgit2/pygit2#1133]
Hello!

I use Saltstack, which depends on pygit2 for Git operations. The [pygit2 version in the Debian repos is very old](https://packages.debian.org/bullseye/python3-pygit2) and could not send a non-SHA1 key to GitHub, so I installed v1.9.0 via Pypi/pip instead.

However, this version did not work either. Possibly because the bundled shared libraries were built against libgit2 v1.4.0 instead of the libgit2 v1.1.0 found on Debian 11 (latest stable). Downgrading to v1.6.1 (which depends on libgit2 v1.1.0) resolved the issues.

So this leads to the following questions:
 - Is there a way to ensure that the wheel runs against the expected library version and throw an immediate error if not?
 - Is there a way to bundle multiple binaries built against different common versions of libgit2 in one wheel?
 - Or is a complete libgit2 bundled and something else is going on?
 - Is this also an issue with libssh2? I am unsure.
 - Is this possibly also an issue on Ubuntu and CentOS? They also do not yet have libgit2 v1.4.0.

Thanks!

Related issue: https://github.com/saltstack/salt/issues/61790

**Comment by jdavid** [comment]
This:

> - Or is a complete libgit2 bundled and something else is going on?

In theory Debian stable has a version of pip new enough, so it's weird.
I tried with Debian oldstable and it worked after updating pip, and tried with Ubuntu 20.04 and it worked out of the box.
So try first to update pip.
Installing the binary wheels may also fail if you're on a platform for which we don't provide binary wheels.
