### ISSUE TITLE
Remove or update documentation at https://pygit2.readthedocs.io/

### ISSUE THREAD

**Issue by jfine2358** [libgit2/pygit2#1157]
Here's a gotcha that caught me.

On the reputable site ReadTheDocs there's stale (2015) docs for your very useful wrapper around libgit2. I read those docs as if they were current, and so greatly underestimated your software. I'm very pleased now to have found https://www.pygit2.org/ and will use it in future.

I don't think I'm the only one. For me the second result for https://www.google.com/search?q=pytgit2+docs is the ReadTheDocs page (and first is https://www.pygit2.org).

Please update or remove the docs on ReadTheDocs. If you can provide a redirection, I think that would be best.

**Comment by jdavid** [comment]
Oh good catch! Removed, thanks.
