### ISSUE TITLE
1.11.1 wheel tags do not match on Ubuntu 20.04

### ISSUE THREAD

**Issue by OrangeDog** [libgit2/pygit2#1179]
Trying to install the latest version, and it won't pick up the wheel.

```python
>>> import packaging.tags
>>> 'cp38-cp38-manylinux_2_24_x86_64' in (str(t) for t in packaging.tags.sys_tags())
True
```

> Skipping link: none of the wheel's tags match: cp38-cp38-manylinux_2_24_x86_64: https://files.pythonhosted.org/packages/64/e4/5262f778b74461435974c5f293a0e128271fe997dd606bee2babf38160c2/pygit2-1.11.1-cp38-cp38-manylinux_2_24_x86_64.whl#sha256=4d6209c703764ae0ba57b17038482f3e54f432f80f88ccd490d7f8b70b167db6 (from https://pypi.org/simple/pygit2/) (requires-python:>=3.8)

No idea why that's not working. All previous releases are fine.

[Full verbose pip install log](https://gist.github.com/OrangeDog/d2763570b1016a3a002b5bce4de19771)

**Comment by jdavid** [comment]
What happes if you first upgrade pip to the latest version?

**Comment by OrangeDog** [comment]
It works if using the latest pip `22.3.1` instead of the system `20.0.2-5ubuntu1.6`.

Which is annoying, but I guess there's not much you can do about it.

**Comment by jdavid** [comment]
Correct, we had to upgrade the wheels to include a newer version of openssl.
Since I expect this to be experienced by many users, I have pinned this issue for the time being.

**Comment by OrangeDog** [comment]
With a bit of investigation, it seems it was fixed by https://github.com/pypa/pip/issues/9077 in pip 20.3.

**Comment by OrangeDog** [comment]
> pygit 1.12.0 Downgrade Linux wheels to manylinux2014

This also fixes it. The stock pip 20.0.2 can now install the wheel.
