### ISSUE TITLE
support libgit2 1.6.x

### ISSUE THREAD

**Issue by MehdiChinoune** [libgit2/pygit2#1193]

**Comment by alerque** [comment]
Yup, an update is needed. Homebrew patched around this with old libraries. Arch Linux is currently hung up on being able to update libgit2 at all until this is addressed. I'm sure there are/will be more.

**Comment by alerque** [comment]
I was able to build the last tagged release of pygit2 against the new libgit2-1.6.3 release by patching out the hard upper limit requirement:

``` console
$ sed -i -e '/LIBGIT2_VER_MINOR/s/5/6/g' src/types.h
```

Apparently the accidentally removed API was the main blocker.

Please still do a new upstream release to mark that dependency change and make it official.
