### ISSUE TITLE
Please consider publishing manylinux_2_17 wheels

### ISSUE THREAD

**Issue by tpanza** [libgit2/pygit2#1209]
On an Oracle Linux 7.9 system, glibc 2.17 is what is installed. It would help immensely if there were wheels published for `manylinux_2_17`, in particular `manylinux_2_17_x86_64`.

Right now, the pip solver finds the `pygit2-1.11.1-cp310-cp310-manylinux_2_24_x86_64.whl`, but skips it as incompatible. It then resorts to attempting a source install, which fails due to `libgit2` headers not being installed.

This is all with a recent `pip`, version pip 23.0.1.

**Comment by jdavid** [comment]
We use again manylinux2014, since 1.12.0
