### ISSUE TITLE
Support libgit2 1.7.x

### ISSUE THREAD

**Issue by MehdiChinoune** [libgit2/pygit2#1231]

**Comment by lazka** [comment]
Arch has a patch here: https://gitlab.archlinux.org/archlinux/packaging/packages/python-pygit2/-/commit/90956c495cb58f39821b33129d5f9900b0b201d1

**Comment by MehdiChinoune** [comment]
Fixed by https://github.com/libgit2/pygit2/commit/1473e8eb
