### ISSUE TITLE
Python 3.12 wheel

### ISSUE THREAD

**Issue by RomainBrault** [libgit2/pygit2#1240]
Would it be possible to push wheels for python 3.12?

libgit2 version 1.7 is not available on ubuntu latest and appveyor do not seems to care about releasing python 3.12 in CI any time soon (see https://github.com/appveyor/ci/issues/3879). Hence waiting for windows wheel might take a long time.

Edit: A new appveyor image with python 3.12 seems to be about to be published.

**Comment by EwoutH** [comment]
AppVeyor updated their images with Python 3.12 (https://github.com/appveyor/ci/issues/3879).
