### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [libgit2/pygit2#1285]
Please release a new version with libgit2 1.8 compatibility.

**Comment by jdavid** [comment]
The tests are failing in AppVeyor, https://ci.appveyor.com/project/jdavid/pygit2/branch/master/job/v4dw1jrduwk69k20
It would be nice if someone that knows Windows volunteers to fix them.

**Comment by jrmarino** [comment]
has there been any progress towards a release?

**Comment by jdavid** [comment]
The issue in libgit2 has been fixed, now waiting for a new release, then the Windows wheels should be available again.

But now it's the macOS wheels that are broken, see https://github.com/libgit2/pygit2/actions/runs/8943488235/job/24568312641

It would be nice if someone that knows macOS volunteers to fix this.
