### ISSUE TITLE
Pygit cant find libgit

### ISSUE THREAD

**Issue by obeleh** [libgit2/pygit2#134]
When I import pygit2 I get the following error:

sjuul@vaio:~/projects/pygit2$ python
Python 2.7.3 (default, Aug  1 2012, 05:16:07) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from pygit2 import *
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pygit2/**init**.py", line 29, in <module>
> > >     from _pygit2 import *
> > > ImportError: libgit2.so.0: cannot open shared object file: No such file or directory

But when I search my folders it's right there where it's supposed to be

sjuul@vaio:~/projects/pygit2$ sudo find / -name "libgit2.so.0"
/usr/local/lib/libgit2.so.0

**Comment by timfeirg** [comment]
I don't think this issue has been resolved on centos 7 as I'm getting the following error:

```python
$ python -c 'import pygit2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
ImportError: libgit2.so.23: cannot open shared object file: No such file or directory
```

I tried `sudo ldconfig` as [the docs](http://www.pygit2.org/install.html#quick-install) says, and I tried `$ sudo LD_RUN_PATH=/usr/local/lib pip install --upgrade pygit2`, didn't get a fix.

@jdavid I clicked into https://github.com/libgit2/pygit2#building-on-nix-including-os-x, it seems like this title was removed, I didn't see any material related to this issue.

@obeleh can we re-open this issue?

**Comment by pypingou** [comment]
I see you're using CentOS 7, Fedora had a somewhat similar problem which was due to a wrong version of pygit2 vs the version of libgit2, could you tell us which ones you're using?

**Comment by pypingou** [comment]
@timfeirg actually, are you using libgit2/pygit2 from the repos? I believe libgit2 is in the CentOS repo while pygit2 is in epel and they should work fine together.

**Comment by jdavid** [comment]
Hello,

If libgit2 is installed from the standard repo, how it is installed in ``/usr/local`` and not ``/usr``? Anyway, ``ldconfig`` should still work, just check first the ``/usr/local/lib`` path is in ``/etc/ld.so.conf``.

The pip install command you show will do nothing if pygit2 is already the latest version, you should pass ``--force-reinstall`` to test that.

You can run ``ldd /usr/lib64/python2.7/site-packages/_pygit2.so`` to see where the dynamic linker will look for libgit2.

Disclaimer: I don't have a CentOS around to test myself.

**Comment by pypingou** [comment]
> If libgit2 is installed from the standard repo, how it is installed in /usr/local and not /usr? 

True there

/me goes back to his corner
