### ISSUE TITLE
Funding

### ISSUE THREAD

**Issue by jdavid** [libgit2/pygit2#230]
I don't know about other contributors, but I work on pygit2 only in my spare time, or occasionally taking a day off from paid work.

Development would go better and faster if it was funded, even if only partially. But I don't know how.

Any ideas welcome!

**Comment by bokehsensei** [comment]
This problem of funding middleware or libraries is so common. Devs start a project in good faith, companies use it, expecting it to be both free and open source, but in reality very rarely contribute back to the developers who often end up working for free. This is no way to run an economy. 
I think there is an opportunity here to create a business around a more fair redistribution of wealth.
Maybe some kind of AppStore for libraries with low friction to get started (free, open-source), but with a common default commercial license for companies that want to profit from it. Of course one can already do that individually, but, as @jdavid mentioned, it's too overwhelming. 
Sorry, I realize this comment isn't directly solving this issue. It just strikes a personal chord.

**Comment by jdavid** [comment]
Follow up in issue #976 

Now I've been accepted in GitHub's sponsor program, let's see whether that works if only a little bit.
