### ISSUE TITLE
Improve installing experience

### ISSUE THREAD

**Issue by jdavid** [libgit2/pygit2#237]
This is a follow up of issue #235

Ideas:
- Provide a tarball of libgit2 (this should be done by the libgit2 team, but it is not)
- Write instructions by system:
  - Install on Debian
  - Install on Mac
  - Install on Windows
  - etc.
- Separate instructions for those who want to use (and contribute :wink: to) the development, unreleased, version

**Comment by techtonik** [comment]
Fixed by #662.

**Comment by tmr232** [comment]
If this is fixed - can someone close this issue?
