### ISSUE TITLE
Coding Guidelines

### ISSUE THREAD

**Issue by heynemann** [libgit2/pygit2#238]
As asked by @jdavid I'd like to start a thread here on the coding guidelines adopted by pygit2 as I got a little confused when submitting my pull request.

Thanks a lot for the help in getting my code merged.

**Comment by tmr232** [comment]
Can this issue be closed? It is very confusing when trying to understand if guidelines are set or not.

**Comment by esc** [comment]
Probably.

**Comment by tmr232** [comment]
@jdavid , can you close the issue?
