### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by philippe-goetz** [libgit2/pygit2#308]
The license issue is only applicable to the license in python files.

This refers also to GPL License Question (https://github.com/libgit2/pygit2/issues/15).

"In addition to the permissions in the GNU General Public License,
 the authors give you unlimited permission to link the compiled
 version of this file into combinations with other programs,
 and to distribute those combinations without any restriction
 coming from the use of this file.  (The General Public License
 restrictions do apply in other respects; for example, they cover
 modification of the file, and distribution when not linked into
 a combined executable.)"

This means that a non-GPL application or library shall import "pyc" (compiled python) not really practicable.

Add the following to the COPYING and change the exception in python files.

"In addition to the permissions in the GNU General Public License,
 the authors give you unlimited permission to import this python file into combinations
 with other programs, and to distribute those combinations without any restriction
 coming from the use of this file.  (The General Public License
 restrictions do apply in other respects; for example, they cover
 modification of the file, and distribution when not imported into
 a combined executable.)"

"link the compiled version of this file" => "import this python file"
"not linked" => "not imported"

**Comment by jdavid** [comment]
No reply so far, closing.

**Comment by tony** [comment]
I think the misunderstanding comes from this libraries own linking of libgit2 (ok), but I doubt that was the intention for the python code was to be GPL+Linking.

The ruby binding is MIT: https://github.com/libgit2/rugged/blob/master/LICENSE

**Comment by tony** [comment]
@jdavid what do you think?
