### ISSUE TITLE
Constants and namespaces

### ISSUE THREAD

**Issue by carlosmn** [libgit2/pygit2#330]
There's something that's been bugging me for a while regarding the libgit2 constants we expose through pygit2. We expose them with the full name, e.g. `GIT_DIRECTION_FETCH`, but we're already inside the our git namespace, so they become `pygit2.GIT_DIRECTION_FETCH`, so now we have two namespaces which mean the same.

Wouldn't it make sense to expose then without the `GIT_` prefix?

**Comment by tmr232** [comment]
Despite the over-writing, having the explicit constant names is useful when digging into the C code.

**Comment by jdavid** [comment]
Closing as stale
