### ISSUE TITLE
config.set_multivar keeps adding new lines

### ISSUE THREAD

**Issue by pypingou** [libgit2/pygit2#373]
Calling multiple times `repo_obj.config.set_multivar()` seems to keep adding empty lines to the configuration file

For example, before calling set_multivar:

```
[core]
    bare = true
    repositoryformatversion = 0
    filemode = true
[multimailhook]
    mailinglist = email
    environment = gitolite
```

after calling set_multivar:

```
[core]
    bare = true
    repositoryformatversion = 0
    filemode = true
[multimailhook]
    mailinglist = email
    environment = gitolite

```

If I call it one more time, then there are two empty lines at the bottom of the file

**Comment by tmr232** [comment]
Is this still relevant? I cannot reproduce it (latest pygit2, Python 2.7.13, Windows 10 x64).

**Comment by jdavid** [comment]
closing then, @pypingou please re-open if you still have the issue
