### ISSUE TITLE
Making Repository.checkout() more pythonic

### ISSUE THREAD

**Issue by djmattyg007** [libgit2/pygit2#412]
I know this has been discussed before, in #139, but it isn't very clear how
far the discussion got. I think it would be nice to have a more pythonic
interface, and the prime example I can think of is to allow passing SHA1
commit hashes to the Repository.checkout() method.

My recent interest in pygit2 stems from the fact that I have started
developing a dependency manager in Python. Unlike other dependency managers
such as Composer, which target a specific language and wrap around many
different code distribution methods, mine will never aim to be anything more
than a wrapper around git.

An important part of dependency management is (obviously) to be able to lock
dependencies to a specific version. I want my users to be able to be able to
specify any sort of reference, be it a branch, a tag, HEAD, or a commit hash.

At the moment, Repository.checkout() handles branches, tags, and HEAD, but it
does not handle commit hashes. This means that I need to verify whether or
not I've been passed a valid commit hash in my own code, and make decisions
based on this. This feels like a violation of the DRY principle, and this
detection could break unnecessarily if the pygit2/libgit2 API changes.
Additionally, adding support for commit hashes more closely mimics the
command-line 'git checkout' command that people are already familiar with.

I would like to get an idea of how other people feel about this proposal
before I start hacking away at the code.

**Comment by jdavid** [comment]
Closing as stale
