### ISSUE TITLE
issue when checking out

### ISSUE THREAD

**Issue by moos3** [libgit2/pygit2#452]
```
 [ERROR   ] Exception 'credential does not implement interface' caught while fetching gitfs remote git@gitlab.local:salt-formula/nodejs.git
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 911, in update
    fetch = origin.fetch()
  File "/usr/lib64/python2.7/site-packages/pygit2/remote.py", line 236, in fetch
    raise self._stored_exception
TypeError: credential does not implement interface
```

rpm installed

```
git-2.1.3-1.el7.centos.x86_64
libgit2-0.21.1-1.el7.x86_64
```

On centos 7

**Comment by ashb** [comment]
This likely means that your version of libgit2 was built without libssh2 support.

**Comment by carlosmn** [comment]
On 25 Mar 2015, at 12:47, Ash Berlin <notifications@github.com> wrote:

> This likely means that your version of libgit2 was built without libssh2 support.

That error message isn�t talking about the libgit2 capabilities, it�s complaining about the object which the credentials callback returned. It does not implement the interface which credential objects must implement.

Either the callback is returning the wrong type of object or the object which was set is not a credentials object. In either case, it�s the caller who has made an error with the API. It is impossible to say what without seeing the code which is generating the object.
