### ISSUE TITLE
How to set the credentials in clone_repository?

### ISSUE THREAD

**Issue by vcforge** [libgit2/pygit2#454]
pygit2.clone_repository('https://github.com/libgit2/libgit2', 'C:\test') will result:
'OSError: Failed to send request: A security error occurred'
How to set the 'credentials' parameter?

**Comment by carlosmn** [comment]
There's a similar (or the same) question [on stackoverflow](http://stackoverflow.com/questions/27220959/how-to-set-the-credentials-in-pygit2-clone-repository) whose poster accepted the answer. Maybe it can help you find out what's wrong.
