### ISSUE TITLE
Trouble installing on Windows

### ISSUE THREAD

**Issue by wme-at-contact-de** [libgit2/pygit2#455]
There seems to be a problem when installing on Windows 7:
error: [Error 5] Access denied: 'c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\.eggs\cffi-0.8.6-py2.7-win32.egg\_cffi_backend.pyd'

Afterwards, the file in question DOES exist at this place and is readable.
This is with a fresh Python 2.7.7 install, with only easy_install added.
libgit2 0.21.2 was compiled with Visual C++ 2008 and made available with set LIBGIT2=...

I have no idea how to fix this, but I'm willing to test potential fixes.

Full log (parts of it are in German, sorry):
C:\Python277>Scripts\easy_install.exe pygit2
Searching for pygit2
Reading https://pypi.python.org/simple/pygit2/
Best match: pygit2 0.21.4
Downloading https://pypi.python.org/packages/source/p/pygit2/pygit2-0.21.4.tar.gz#md5=8a3d02eded2bef2e0af18172814eec32
Processing pygit2-0.21.4.tar.gz
Writing c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\setup.cfg
Running pygit2-0.21.4\setup.py -q bdist_egg --dist-dir c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\egg-dist-tmp-tq0y5e
Searching for cffi
Reading https://pypi.python.org/simple/cffi/
Best match: cffi 0.8.6
Downloading https://pypi.python.org/packages/source/c/cffi/cffi-0.8.6.tar.gz#md5=474b5a68299a6f05009171de1dc91be6
Processing cffi-0.8.6.tar.gz
Writing c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\temp\easy_install-zmxliv\cffi-0.8.6\setup.cfg
Running cffi-0.8.6\setup.py -q bdist_egg --dist-dir c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\temp\easy_install-zmxliv\cffi-0.8.6\egg-dist-tmp-hwxyjn
_cffi_backend.c
c/_cffi_backend.c(5317) : warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
c/_cffi_backend.c(5318) : warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
c/_cffi_backend.c(5319) : warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
c/_cffi_backend.c(5320) : warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
ffi.c
c/libffi_msvc\ffi.c(122) : warning C4018: '>': Konflikt zwischen 'signed' und 'unsigned'
prep_cif.c
types.c
win32.c
   Bibliothek "build\temp.win32-2.7\Release\c_cffi_backend.lib" und Objekt "build\temp.win32-2.7\Release\c_cffi_backend.exp" werden erstellt.

Installed c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4.eggs\cffi-0.8.6-py2.7-win32.egg
Searching for pycparser
Reading https://pypi.python.org/simple/pycparser/
Best match: pycparser 2.10
Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f
Processing pycparser-2.10.tar.gz
Writing c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\temp\easy_install-phxmev\pycparser-2.10\setup.cfg
Running pycparser-2.10\setup.py -q bdist_egg --dist-dir c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\temp\easy_install-phxmev\pycparser-2.10\egg-dist-tmp-wjomir
zip_safe flag not set; analyzing archive contents...

Installed c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4.eggs\pycparser-2.10-py2.7.egg
pygit2_cffi_18eab927xbf062fb5.c
   Bibliothek "c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\pygit2__pycache__\Release\pygit2__pycache__\pygit2_cffi_18eab927xbf062fb5.lib" und Objekt "c:\users\wme\appdata\local\temp\
_install-u2jzwv\pygit2-0.21.4\pygit2__pycache__\Release\pygit2__pycache__\pygit2_cffi_18eab927xbf062fb5.exp" werden erstellt.
error: [Error 5] Zugriff verweigert: 'c:\users\wme\appdata\local\temp\easy_install-u2jzwv\pygit2-0.21.4\.eggs\cffi-0.8.6-py2.7-win32.egg\_cffi_backend.pyd'

**Comment by techtonik** [comment]
Fixed by #662.

**Comment by tmr232** [comment]
@jdavid Can you close the issue?

**Comment by jdavid** [comment]
yes, thanks @tmr232 for looking at the open issues

**Comment by tmr232** [comment]
@jdavid You're welcome. There are some more issues closed by the same commit if you look at #662
