### ISSUE TITLE
Updated windows installation guide

### ISSUE THREAD

**Issue by weirdall** [libgit2/pygit2#482]
If you're interested, this is what I did to compile libgit2.

Download Visual Studio 10 Express (Python 3.4)
mkdir C:/dev/
download libgit2 from https://github.com/libgit2/libgit2/archive/v0.22.0.tar.gz
Move file to C:/dev
unpack archive v0.22.0.tar.gz
set LIBGIT2=C:/dev/libgit2-0.22.0
cd libgit2-0.22.0
cmake . -DSTDCALL=OFF -DCMAKE_INSTALL_PREFIX=%LIBGIT2% -G "Visual Studio 10"
cmake --build . --config release --target install
ctest -v

**Comment by weirdall** [comment]
And had to finish it with:
cp C:/dev/libgit2/bin/git2.dll c:\windows\system32

After this I was able to do pip install pygit2

**Comment by carlosmn** [comment]
Putting libraries into the system's directory is bad news. libgit2 should not look to programs as being part of Windows; it can lead to problems when loading, especially when it has not information about which version it is.

The dlls you need for your application should be alongside your application.

**Comment by weirdall** [comment]
Ok, thanks for that warning. 
However I cannot build pygit2 with the instructions provided. Can you tell me how to do it without putting libraries into the system directory? Perhaps with the guide I made?
With kind regards,
Floris Groenendijk

Date: Thu, 5 Feb 2015 12:18:04 -0800

**Comment by Sheeo** [comment]
@weirdall you need to put it anywhere in your $PATH, so that pip can find it.

For windows, there is no standard place for this, so I suggest putting it in your application directory and doing `pip install` from there, since your path typically contains `.`.

**Comment by techtonik** [comment]
Fixed by #662.
