### ISSUE TITLE
diff does not generate any output: pygit2

### ISSUE THREAD

**Issue by zack211** [libgit2/pygit2#484]
I am trying to do something similar to "git show" . So when I try to print the result of diff , I don't get what I am expecting. I am referring the pygit2 documentation. What is the problem here?

import pygit2
repo=pygit2.Repository('/home/repository')

t0=repo.revparse_single('HEAD').tree
t1=repo.revparse_single('HEAD^').tree

> > > repo.diff(t0,t1)
> > > <_pygit2.Diff object at 0x7fc46eeb0470>
> > > out=repo.diff(t0,t1)
> > > print out
> > > <_pygit2.Diff object at 0x7fc46eeb0410>

**Comment by jdavid** [comment]
Here http://www.pygit2.org/diff.html#pygit2.Diff.patch

So you can try:

    >>> print out.patch

Is that what you want?

**Comment by zack211** [comment]
Yes. It works! Thanks. Btw I want to find all the code changes in a repository. Is below the right way to do? Will this ensure that I get all the differences if I find the diff between "t0" and "t1" ? Thanks

t0=repo.revparse_single('HEAD').tree
t1=repo.revparse_single('HEAD^').tree

**Comment by jdavid** [comment]
You can make it shorter:

    >>> repo.diff('HEAD', 'HEAD^')

It's in the docs.
