### ISSUE TITLE
Expose checkout strategy in clone_repository()

### ISSUE THREAD

**Issue by cfs-pure** [libgit2/pygit2#485]
Currently there is no way to pass in the checkout strategy git_clone() in clone_repository().  This makes simulating 'git clone --no-checkout' impossible.  A possible solution is adding a checkout_strategy argument to pygit2.clone_repository(), that when not set to None, would pass the set of flags into opts.checkout_opts.checkout_strategy (after initializing opts.checkout_opts).

**Comment by carlosmn** [comment]
Since you closed the pull request yourself, are you not interested in this anymore?

**Comment by jdavid** [comment]
Closing as stale
