### ISSUE TITLE
trouble removing files

### ISSUE THREAD

**Issue by brown** [libgit2/pygit2#496]
When running pygit2 tests, I saw failures because of an inability to remove
some files created by the tests.  The files were in directories for which I did
not have write permission.  My umask is 0027 ... perhaps that's to blame.
In any case, I modified force_rm_handle in test/utils.py so that it makes
both the directory and the file writable before calling remove_path.  The
code now looks like this:

def force_rm_handle(remove_path, path, excinfo):
    os.chmod(
        os.path.dirname(path),
        os.stat(os.path.dirname(path)).st_mode | stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH
    )
    os.chmod(
        path,
        os.stat(path).st_mode | stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH
    )
    remove_path(path)

**Comment by carlosmn** [comment]
What OS are you on? What filesystem? The code in the test utils is already making sure we can delete the files in troublesome situations.

**Comment by brown** [comment]
OS is Ubuntu Linux 14.04.  File system type is ext4.  Here's
a typical error ... failure to remove file in force_rm_handle:

>       remove_path(path)
E       OSError: [Errno 13] Permission denied:
'/tmp/tmpL7ADPo/testrepo.git/objects/10/2374bdb1e8efca5e66cded18fd8f30571654a5'

Here's what the file and its directory look like:

brown [35311]  ls -al
/tmp/tmpn4Vg0i/testrepo.git/objects/10/2374bdb1e8efca5e66cded18fd8f30571654a5
-rw-rw--w- 1 brown eng 209 Jan 16 10:35
/tmp/tmpn4Vg0i/testrepo.git/objects/10/2374bdb1e8efca5e66cded18fd8f30571654a5

brown [35312]  ls -ald /tmp/tmpn4Vg0i/testrepo.git/objects/10
dr-xr-xr-x 2 brown eng 4096 Feb 19 12:48
/tmp/tmpn4Vg0i/testrepo.git/objects/10

**Comment by jdavid** [comment]
we don't remove files anymore, now this is handled by pytest
