### ISSUE TITLE
Create a ppa or submitting package to ubuntu/debian.

### ISSUE THREAD

**Issue by yesimon** [libgit2/pygit2#498]
I noticed during installation on Ubuntu that versions of pygit2 should be in concordance with libgit2 in a very specific way. This is a perfect use case for submitting a package to ubuntu or debian that versions up with the included libgit2 in stable releases. In contrast pip is not good for this because you have to specify the version manually after checking library versions of libgit2 manually, otherwise pip just installs the newest version.

Just a suggestion!

**Comment by carlosmn** [comment]
There is already a package for pygit2. It is currently in the NEW queue.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769421

**Comment by yesimon** [comment]
Cool! That's great!

**Comment by ajnelson-nist** [comment]
So you're aware: The package in Ubuntu is present for the 15.10 release, but doesn't do the complete build.  I'm hoping there's some last step they've missed that'll be obvious to you.

https://bugs.launchpad.net/ubuntu/+source/python-pygit2/+bug/1475431/
