### ISSUE TITLE
Question: use Index object for adding and committing new files + changes?

### ISSUE THREAD

**Issue by finjulhich** [libgit2/pygit2#500]
After a python process that creates new files and changes existing text files in a work directory, I currently do the following at the shell:

cd <workdir>
git add -A .                             # track all un-tracked files
git commit -a -m "message"  # do a commit

How can I do it from the python script itself with pygit2?

**Comment by jdavid** [comment]
Hello, you can add the files to the index with
http://www.pygit2.org/working-copy.html#pygit2.Index.add_all

Do not forget to save changes to the index file with
http://www.pygit2.org/working-copy.html#pygit2.Index.write

To save the index to the object database and get the oid of the new tree
http://www.pygit2.org/working-copy.html#pygit2.Index.write_tree

Then to create a commit
http://www.pygit2.org/objects.html#pygit2.Repository.create_commit

**Comment by finjulhich** [comment]
Thanks, so I did:

repo.index.add_all()
repo.index.write()

# at this point I see the untracked files tracked
treeoid = repo.index.write_tree()

# then creating the commit
oid1= repo.create_commit('refs/heads/master', pygit2.Signature(...), pygit2.Signature(...), 'message', treeoid, [lastcommit] )

I found that if I passed [] instead of [lastcommit] for parents, create_commit failed.

Is there an option to make it take the last commit by default, or do I explicity use the walker to find the last commit?

**Comment by finjulhich** [comment]
I got it. I can just use repo.head.target

**Comment by jdavid** [comment]
closing, reopen if there is something left
