### ISSUE TITLE
pip install pygit2: compile errors in pygit2 cffi

### ISSUE THREAD

**Issue by silentsnooc** [libgit2/pygit2#501]
(on Windows)

I just can't find a solution for this problem here: http://codepad.org/NtZ5p5FS

I try to install pygit2:

> python -m pip install pygit2 > pip.pygit2.log

The essential part is the compilation of cffi for pygit2. I've installed Visual C++ Compiler for Python as recommended by the setup but it is very unhappy about the syntax as it throws a lot of compile errors:

> running build_ext
> building 'pygit2_cffi_a2d0f8b5x5470904' extension
> creating c:\users\stefan\appdata\local\temp\pip-build-a6yeml\pygit2\pygit2\__pycache__\Release
> creating c:\users\stefan\appdata\local\temp\pip-build-a6yeml\pygit2\pygit2\__pycache__\Release\pygit2
> creating c:\users\stefan\appdata\local\temp\pip-build-a6yeml\pygit2\pygit2\__pycache__\Release\pygit2\__pycache__
> C:\Users\Stefan\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Dev\libgit2\include -IC:\Python27\include -IC:\Python27\PC /Tcpygit2\__pycache__\pygit2_cffi_a2d0f8b5x5470904.c /Foc:\users\stefan\appdata\local\temp\pip-build-a6yeml\pygit2\pygit2\__pycache__\Release\pygit2\__pycache__\pygit2_cffi_a2d0f8b5x5470904.obj
> pygit2_cffi_a2d0f8b5x5470904.c
> pygit2\__pycache__\pygit2_cffi_a2d0f8b5x5470904.c(209) : error C2143: syntax error : missing ')' before '*'
> pygit2\__pycache__\pygit2_cffi_a2d0f8b5x5470904.c(209) : error C2143: syntax error : missing '{' before '*'
> pygit2\__pycache__\pygit2_cffi_a2d0f8b5x5470904.c(209) : error C2059: syntax error : ')'
> pygit2\__pycache__\pygit2_cffi_a2d0f8b5x5470904.c(210) : error C2054: expected '(' to follow 'p'
> // ... many many more syntax errors (see link above)

Does anybody know what the problem is here?

Posted this question on SO: http://stackoverflow.com/questions/28879772/pip-install-pygit2-compile-errors-in-pygit2-cffi

**Comment by jdavid** [comment]
Does issue #482 help you?

**Comment by jdavid** [comment]
Maybe you could post the contents of the file ``pygit2_cffi_a2d0f8b5x5470904.c``

Be sure you are using v0.22.1, and if it fails still, try with the development version of pygit2 (the master branch).

**Comment by silentsnooc** [comment]
Sorry I'm not further investigating this. I don't know the reasons why it is so hard to install pygit2 and I don't understand why libgit2 does not want to success on every unit test (http://stackoverflow.com/questions/28915860/able-to-build-libgit2-but-ctest-fails) but I'm already tired of trying to be honest. No offense.

**Comment by jdavid** [comment]
okey
