### ISSUE TITLE
The API have some problems ？

### ISSUE THREAD

**Issue by 8427003** [libgit2/pygit2#509]
![qq 20150401191153](https://cloud.githubusercontent.com/assets/5475231/6939844/1c570322-d8a3-11e4-801a-28d434274750.png)

**Comment by pypingou** [comment]
There are defined here https://github.com/libgit2/pygit2/blob/master/src/pygit2.c#L274-L281

**Comment by 8427003** [comment]
@pypingou thanks！ by the way，“GIT_STATUS_WT_MODIFIED” What does 'WT' stand for

**Comment by pypingou** [comment]
No idea :)

**Comment by 8427003** [comment]
@pypingou oh,You are a bad man! You know it, I find some evidence in your gitsync。I am a novice，very sorry ask such a question

**Comment by pypingou** [comment]
I have no idea no, I am not a pygit2 dev

**Comment by pypingou** [comment]
Just had a thought: Working Tree maybe?

**Comment by 8427003** [comment]
@pypingou thanks! you are a good man!
