### ISSUE TITLE
Adding git repository in tests breaks git submodules "--recursive" behavior

### ISSUE THREAD

**Issue by rutsky** [libgit2/pygit2#515]
[Recently](https://github.com/libgit2/pygit2/commit/1361b2cce90f3c29b7b9d0f0f5c98f6a6eee8e75) `test/data/testrepo` directory was added with actual git repository contents.
This breaks git submodule's `--recursive` functionality:

```
$ git clone git@github.com:libgit2/pygit2.git
...
$ cd pygit2
$ git checkout 1361b2cce90f3c29b7b9d0f0f5c98f6a6eee8e75
...
$ git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'test/data/testrepo'
$ echo $?
1
$
```

Which breaks tools that rely on recursive submodules checkout, e.g. see this pip bug: https://github.com/pypa/pip/issues/2705

**Comment by carlosmn** [comment]
The mistakenly-added submodule entry has been removed.
