### ISSUE TITLE
Add ability to detect stale refs, or at least the ability to list remote refs

### ISSUE THREAD

**Issue by terminalmage** [libgit2/pygit2#524]
Please correct me if I am wrong, but I don't see a way to detect stale refs. So, if a branch/tag is removed from the remote repository, this change is not affected the next time you fetch that remote with pygit2.

**Comment by carlosmn** [comment]
If the remote is configured to do so, libgit2 will prune the remote-tracking branches. The function to perform this step manually is however not exposed in pygit2.

**Comment by terminalmage** [comment]
Well, the end goal is to prune stale branches/tags, so if this functionality can be turned on in pygit2 that would accomplish what I was looking to do. But a function to list stale refs would have use in and of itself.

**Comment by carlosmn** [comment]
The logic to do detect which remote-tracking branches to remove is not currently in an exportable shape, it's just part of the function which removes them rather than anything which creates a list.

**Comment by jdavid** [comment]
This was fixed by #825
