### ISSUE TITLE
Incorrectly depends on CFFI universally

### ISSUE THREAD

**Issue by Julian** [libgit2/pygit2#539]
The `install_requires` contains `cffi`, but this is incorrect -- running `pip install -U pygit2` on a PyPy installation with CFFI older than a version uploaded to PyPI will break the PyPy install as it tries to update the vendored CFFI to the newer version. The setup.py requirement should specifically say that CFFI is a dependency only on things other than PyPy (via environment markers, an if block, etc., depending on the methods used to build dists)

https://github.com/pyca/cryptography/pull/1695 has some background for a similar problem.

**Comment by webknjaz** [comment]
Addressed by manylinux1 wheels shipped with v0.28.0.

@jdavid you can close this.

**Comment by jdavid** [comment]
manylinux1 wheels still require cffi

But looking at the changes in cryptography's setup.py this may have already been solved by Pypy. In cryptography the referenced commit is https://github.com/pyca/cryptography/pull/1695/commits/4cf381137643c2d78e8631f3f439daef62a97a67

But in commit https://github.com/pyca/cryptography/commit/ca2055f9822def12ec47a7b886be7c13c590b8fa they have reverted that change.

So this is probably not needed anymore. Closing.
