### ISSUE TITLE
Error in Signature when pushing to a remote repository

### ISSUE THREAD

**Issue by ahmed-taj** [libgit2/pygit2#541]
Hi,

I'm facing problem when pushing using pygit2 v0.21.3 (in windows) .
here is my code :

    import pygit2 as git
    repo = git.Repository("path/to/my/repo.git") # just for testing,it will not be local

    for rem in repo.remotes:
        rem.push_url = rem.url
        rem.credentials = git.UserPass("user","passowrd")
        sig = git.Signature("user","user@example.com")

        rem.push('refs/heads/master',sig,"message")

But,I always received this message :

    Traceback (most recent call last):
      File "C:\test.py", line 190, in <module>
        rem.push('refs/heads/master',sig,"message")
      File "C:\Python34\lib\site-packages\pygit2-0.21.3-py3.4-win32.egg\pygit2\remote.py",line 353, in push
        err = C.git_push_update_tips(push, ptr, to_bytes(message))
    TypeError: initializer for ctype 'git_signature *' must be a cdata pointer, not bytes

**PS**: I also got this exact same error on Ubuntu with v0.22.0 

Thanks.

**Comment by carlosmn** [comment]
Are you sure you updated to the v0.22.0 release of pygit2? Both v0.22.0 and v0.22.1 contain f68b266 which moved away from performing the push manually to use libgit2's `git_remote_push()` and it should not cause this error.

**Comment by ahmed-taj** [comment]
Yes, I did in Ubuntu .(pygit2 `v0.22.0` and libgit2 `v.22.2').

Well, today I update both pygit2 and libgit2 , so  now my versions are pygit2 `v0.22.1`,and libgit2 `v.22.3'). It works fine :) without the mentioned error or any segmentation fault.

Thank you for your help.
