### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by toast12** [libgit2/pygit2#542]
Hi,

I run vcvarsall.bat for visual studio 2008 and then try to install pygit2 but hitting this error:

git2.lib(hash_win32.obj) : error LNK2019: unresolved external symbol **imp__CryptAcquireContextA@20 referenced in function _hash_cryptoapi_prov_init
git2.lib(hash_win32.obj) : error LNK2019: unresolved external symbol __imp__CryptReleaseContext@8 referenced in function _hash_cryptoapi_prov_shutdown
git2.lib(hash_win32.obj) : error LNK2019: unresolved external symbol __imp__CryptCreateHash@20 referenced in function _hash_cryptoapi_init
git2.lib(hash_win32.obj) : error LNK2019: unresolved external symbol __imp__CryptDestroyHash@4 referenced in function _hash_cryptoapi_init
git2.lib(hash_win32.obj) : error LNK2019: unresolved external symbol __imp__CryptHashData@16 referenced in function _hash_cryptoapi_update
git2.lib(hash_win32.obj) : error LNK2019: unresolved external symbol __imp__CryptGetHashParam@20 referenced in function _hash_cryptoapi_final
git2.lib(findfile.obj) : error LNK2019: unresolved external symbol __imp__RegCloseKey@4 referenced in function _win32_find_git_in_registry
git2.lib(findfile.obj) : error LNK2019: unresolved external symbol __imp__RegQueryValueExW@24 referenced in function _win32_find_git_in_registry
git2.lib(findfile.obj) : error LNK2019: unresolved external symbol __imp__RegOpenKeyExW@20 referenced in function _win32_find_git_in_registry
git2.lib(winhttp.obj) : error LNK2019: unresolved external symbol __imp__CoUninitialize@0 referenced in function _fallback_cred_acquire_cb
git2.lib(winhttp.obj) : error LNK2019: unresolved external symbol __imp__CoCreateInstance@20 referenced in function _fallback_cred_acquire_cb
git2.lib(winhttp.obj) : error LNK2019: unresolved external symbol __imp__CoInitializeEx@8 referenced in function _fallback_cred_acquire_cb
c:\toolchain\src\pygit2-0.22.0\pygit2-0.22.0\pygit2__pycache**\pygit2_cffi_dde02c5x5470904.pyd : fatal error LNK1120: 12 unresolved externals

Checked on google and it says I need to add Advapi32.lib but how do I add it? I tried adding to LIBPATH and PATH, but it doesn't resolve the issue

**Comment by toast12** [comment]
I am still unable to compile on windows. Anybody?

**Comment by toast12** [comment]
In case someone is looking for an answer here:

I resolved this yesterday. Initially I was building libgit2 with shared-libs=off. After I removed that part and rebuilt libgit2 things sorted out. During pygit2 build, I also had to add libgit2/lib in my PATH. Hope this helps

**Comment by eraxillan** [comment]
You just should link additional Windows-specific libraries, e.g. in this way:
#pragma comment( lib, "Advapi32.lib" )
#pragma comment( lib, "Rpcrt4.lib" )
#pragma comment( lib, "Ole32.lib" )
#pragma comment( lib, "Winhttp.lib" )
#pragma comment( lib, "Crypt32.lib" )

**Comment by techtonik** [comment]
Builds are crunching ok now - https://ci.appveyor.com/project/jdavid/pygit2/history Close the ticket?

**Comment by tmr232** [comment]
@jdavid
