### ISSUE TITLE
pygit2 build issue on OS X

### ISSUE THREAD

**Issue by toast12** [libgit2/pygit2#545]
Hi,

I am trying to build pygit2 on os x 10.8.0 with python 2.7.9 and hitting this error:

pygit2-0.22.0/pygit2/**pycache**/pygit2_cffi_93ecb84x5470904.so': dlopen(pygit2-0.22.0/pygit2/**pycache**/pygit2_cffi_93ecb84x5470904.so, 2): Symbol not found: _iconv
  Referenced from: pygit2-0.22.0/pygit2-0.22.0/pygit2/__pycache__/pygit2_cffi_93ecb84x5470904.so
  Expected in: flat namespace
 in pygit2-0.22.0/pygit2/**pycache**/pygit2_cffi_93ecb84x5470904.so

Any suggestion on how to resolve this?

**Comment by toast12** [comment]
Resolved this by adding -liconv as a linker option

**Comment by webknjaz** [comment]
The broader fix would be building OS-specific wheels for OS X and distributing them via PyPI.

**Comment by webknjaz** [comment]
This will be addressed by https://github.com/libgit2/pygit2/issues/900

**Comment by jdavid** [comment]
Now we have wheels for OS X, implemented in PR #988
