### ISSUE TITLE
Provide quick tutorial in main page of documentation

### ISSUE THREAD

**Issue by cool-RR** [libgit2/pygit2#549]
Should be approximately one page to show using the main features of pygit2.

**Comment by jdavid** [comment]
Closing as stale

**Comment by cool-RR** [comment]
It might be five years old, but as far as can see it's still relevant.

**Comment by jdavid** [comment]
It's unclear what the main features are, probably those depend on the reader. So it would be much more than 1 page.
For comparison what GitPython has is a lengthy tutorial, https://gitpython.readthedocs.io/en/stable/tutorial.html
The documentation needs much love but I will only be able to make small improvements.
