### ISSUE TITLE
I can't push code to remote, return -7 error code.

### ISSUE THREAD

**Issue by kuailewangzi0328** [libgit2/pygit2#553]
I use libgit2 v0.22.3 and pygit2 v0.22.1

first, I clone the repo from github by ssh procotol like follow code :

```
repo = pygit2.clone_repository(remoteUrl, localPath,credentials=credentials_test) 
repo.remotes["origin"].sideband_progress = sideband_progress_test
repo.remotes["origin"].transfer_progress = transfer_progress_test
repo.remotes["origin"].update_tips = update_tips_test
return repo
```

and it excute success . I get the repository and read the remote success like follow code :

```
repo = discoverRepository(current_repository)
    for remote in repo.remotes:
        print remote.name, "----->",remote.url
        print remote.credentials
        print remote.sideband_progress
        print remote.transfer_progress
        print remote.update_tips
```

I also can edit content, and commit the change. It all success. but when I want push these commit to remote like follow code ,It always raise GitError ,and error code is -7. no other reason.

```
repo = discoverRepository(current_repository)
repo.remotes[remoteName].push(['refs/heads/master'],getDefaultAuthor(),"ceshi push")
```

 Traceback (most recent call last):
  File "/Users/changdengkai/worksapce/androidWorkspace/testPyGit2/testRepository.py", line 153, in <module>
    mainTest()
  File "/Users/changdengkai/worksapce/androidWorkspace/testPyGit2/testRepository.py", line 142, in mainTest
    pushBySSHRemote("origin");
  File "/Users/changdengkai/worksapce/androidWorkspace/testPyGit2/testRepository.py", line 124, in pushBySSHRemote
    repo.remotes[remoteName].push(['refs/heads/master'],getDefaultAuthor(),"ceshi push")
  File "/Library/Python/2.7/site-packages/pygit2-0.22.1-py2.7-macosx-10.10-intel.egg/pygit2/remote.py", line 322, in push
    check_error(err)
  File "/Library/Python/2.7/site-packages/pygit2-0.22.1-py2.7-macosx-10.10-intel.egg/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: err -7 (no message provided)

I already try many way like change repo's url  from github to gitlab,  or change push func's param . and replace other version libgit2 (0.22.0) and pygit2(0.22.0), but still no effect. 

please help me !!!  thanks very much !!!

**Comment by carlosmn** [comment]
`GIT_EUSER` is never generated by libgit2 itself, so it looks like it might be due to pygit2 noticing an error but not picking it up once the stack rolls back to python.

I do notice that you're not providing any credentials for the push, so it seems like that pygit2's callback wrapper is  the one generating the error.

**Comment by kuailewangzi0328** [comment]
yes, I saw the source code and It seems like pygit2's callback wrapper  generated this error. but I don't know what spec specific reason. for you notice. I put the credentials function in clone function. and I clone the repo by ssh protocol success . So it mean the credentials is valid. and I also try set credentials before push again. but it still raise same error. the biggest problem is I don't what type this error is. network or io or Permission……even when I used pygit2 0.22.0 ,it just show me a git error raised and no error num…… I really don't understand why pygit2 don't show the error's reason more specific……

**Comment by carlosmn** [comment]
It's precisely because clone works that I think it's due to the credentials. In the code you've posted here, you are not setting any credentials callbacks at all.

    repo.remotes[remoteName].push(['refs/heads/master'],getDefaultAuthor(),"ceshi push")

If you want to set the credentials callback, yo must set it on the instance

```python
remote = repo.remotes[remoteName]
remote.credentials = your_credentials_callback
remote.push(['refs/heads/master:refs/heads/master']
```

**Comment by kuailewangzi0328** [comment]
I'm very very thanks for your help ! actually I wrote code like following after I received your last reply :

    repo = discoverRepository(current_repository)
    repo.remotes[remoteName].credentials = credentials_test
    repo.remotes[remoteName].push(['refs/heads/master:refs/heads/master'])

but it still doesn't work.  now I just modify few code and make it looks like following:

    repo = discoverRepository(current_repository)
    remote = repo.remotes[remoteName]
    remote.credentials = credentials_test
    remote.push(['refs/heads/master:refs/heads/master'])

please forgive my stupid !! I don't understand why it can make this issue. actually in my poor mind I even thought these two kind of style of writing are same in python.

whatever, you save my work ,I already try solve it for two days . actually I planed give up it  and try to use libgit2 immediately this afternoon. thank you again……

**Comment by jdavid** [comment]
Since version 1.2.1 we properly raise errors from callbacks.
