### ISSUE TITLE
pygit2 (Ver 0.23.0) cmake libssh2 not found

### ISSUE THREAD

**Issue by santublr** [libgit2/pygit2#556]
Hello,

The libssh2 not found error found during cmake. The libssh2 package is available on the system.

rpm -ql libssh2
/usr/lib64/libssh2.so.1
/usr/lib64/libssh2.so.1.0.1
/usr/share/doc/libssh2-1.4.2
/usr/share/doc/libssh2-1.4.2/AUTHORS
/usr/share/doc/libssh2-1.4.2/COPYING
/usr/share/doc/libssh2-1.4.2/ChangeLog
/usr/share/doc/libssh2-1.4.2/NEWS
/usr/share/doc/libssh2-1.4.2/README
/usr/lib/libssh2.so.1
/usr/lib/libssh2.so.1.0.1
/usr/share/doc/libssh2-1.4.2
/usr/share/doc/libssh2-1.4.2/AUTHORS
/usr/share/doc/libssh2-1.4.2/COPYING
/usr/share/doc/libssh2-1.4.2/ChangeLog
/usr/share/doc/libssh2-1.4.2/NEWS
/usr/share/doc/libssh2-1.4.2/README

[root@xxxx build]#  cmake .. -DCMAKE_INSTALL_PREFIX=/opt/perforce/demo_setup/git-fusion/libexec/
CMake Error at CMakeLists.txt:16 (CMAKE_POLICY):
  Policy "CMP0015" is not known to this version of CMake.

-- REQUIRED_VARS  (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
-- http-parser was not found or is too old; using bundled 3rd-party sources.
-- checking for module 'libssh2'
--   package 'libssh2' not found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Configuring incomplete, errors occurred!

Thx,
Santosh

**Comment by carlosmn** [comment]
Those file are not enough to compile against libssh2. If you want to install libgit2 with libssh2 support, you need to install libssh2's development package before building libgit2.

**Comment by santublr** [comment]
Got the libssh2-devel installed. Getting the below error:
CMake Error at CMakeLists.txt:16 (CMAKE_POLICY):
  Policy "CMP0015" is not known to this version of CMake.


-- REQUIRED_VARS  (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
-- http-parser was not found or is too old; using bundled 3rd-party sources.
-- Configuring incomplete, errors occurred!

**Comment by carlosmn** [comment]
That error is not related to libssh2. Your CMake version is too old.

**Comment by jdavid** [comment]
Closing, by the way we have manylinux wheels now.
