### ISSUE TITLE
remove branch/reference from the server repository

### ISSUE THREAD

**Issue by MELLITI-Alaeddine** [libgit2/pygit2#562]
Assuming that we have a remote branch called 'i18n' and we would like to remove this branch from the server repository.
# get the branch

branch = self.repo.lookup_branch('i18n')
# delete the branch locally

branch.delete()
how to push the removed branch: how can we remove it from the server repository ???

idem for reference

**Comment by carlosmn** [comment]
Deleting references is done by pushing an empty local reference to it, like you can do with git's push command. So pushing `[":refs/heads/i18n"]` would delete the `i18n` branch on the remote.

**Comment by sylva91** [comment]
i've just tried that and it's not working, the error i'm getting after the push of the deleted branch is : GitError: deleted reference

**Comment by ioanb7** [comment]
Any update on this?

**Comment by ioanb7** [comment]
What @wael216  said works. More info on https://stackoverflow.com/questions/35763709/delete-remote-branch
