### ISSUE TITLE
Please support the git_index_add_frombuffer()

### ISSUE THREAD

**Issue by ytrezq** [libgit2/pygit2#575]
Working from windows, and I realize it’s hard to work with paths longer than 260 characters without [ꜱᴜᴀ](https://en.wikipedia.org/wiki/Windows_Services_for_UNIX) _(where it’s very hard to get python working on the posix subsystem)_.

So please support this function, so I can work with paths that don’t exist.

**Comment by carlosmn** [comment]
You don't *need* this function. This is a convenience function for writing a buffer into the object database and adding the entry to the index. pygit2 allows you to do both of these things with `Repository.write()` and `Index.add()` together with a `IndexEntry` you provide.

**Comment by ytrezq** [comment]
@carlosmn : Does it means, pygit2 already allow to work with non existing files    ?

**Comment by carlosmn** [comment]
You can add entries to the index as I described, regardless of what exists on the workdir. This is a rather normal part of Git operations.

**Comment by ytrezq** [comment]
@carlosmn : Ok, were are those functions documented ?

**Comment by ytrezq** [comment]
@jdavid why did you close this? Is the way to add files from a network buffer now documented? And where?

**Comment by jdavid** [comment]
The documentation is in https://www.pygit2.org/ but it's true that Repository.write() is missing, just added it in commit eea05940.

So as @carlosmn explained you have to create the object with Repository.write() then create the IndexEntry object, and finally add the index entry to the index with Index.add().

Of course a recipe in the documentation would be nice.
