### ISSUE TITLE
pip install pygit2 into virtualenv, I had to pass extra options to pip to get it to work

### ISSUE THREAD

**Issue by bkcsfi** [libgit2/pygit2#576]
This is what I had to do to get pygit2 installed into a virtualenv on ubuntu 14.04
1. activate virtualenv (I'm setting up powerline, so using the same virtualenv for both powerline and pygit2)
2. set LIBGIT2 $VIRTUAL_ENV
   (this sets global var in fish shell.. use export LIBGIT2= ... for bash)
   
   in this example LIBGIT2 is /home/bkc/PythonEnvironments/powerline
3. download and build libgit2-0.23.2 in the virtualenv
   
   ```
   cd $LIBGIT2
   wget wget https://github.com/libgit2/libgit2/archive/v0.23.2.tar.gz
   tar zxf v0.23.2.tar.gz 
   cd libgit2-0.23.2/
   cmake . -DCMAKE_INSTALL_PREFIX=$LIBGIT2
   make
   make install
   ```
4. install pygit2 via pip
   
   using --global-option was required to get include dir, library and rpath set because exported LDFLAGS and CFLAGS were being ignored by pip
   
   ```
   pip install  pygit2 --global-option=build_ext --global-option="-I/home/bkc/PythonEnvironments/powerline/libgit2-0.23.2/include" --global-option="-L/home/bkc/PythonEnvironments/powerline/lib" --global-option="--rpath=/home/bkc/PythonEnvironments/powerline/lib"
   ```
5. profit

```
   $ python
   Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
   [GCC 4.8.2] on linux2
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import pygit2
   >>>
```

**Comment by webknjaz** [comment]
Addressed by manylinux1 wheels shipped with v0.28.0.

@jdavid you can close this.
