### ISSUE TITLE
Please support an equivelent of git-repack.

### ISSUE THREAD

**Issue by ytrezq** [libgit2/pygit2#578]
Hello, I have a problem where the official git project have a nasty bug that prevent any repack command to be successful on my repo _(the process crash when creating a packfile)_.

**Comment by jdavid** [comment]
See https://github.com/libgit2/libgit2/issues/3247

**Comment by ytrezq** [comment]
@jdavid how is this other issue related to this one?

**Comment by jdavid** [comment]
In that issue they discuss repack, see for example this comment https://github.com/libgit2/libgit2/issues/3247#issuecomment-503914427

So if one day libgit2 implements repack then we will be able to wrap it.
