### ISSUE TITLE
CFFI Warnings

### ISSUE THREAD

**Issue by jpulec** [libgit2/pygit2#584]
Noticed that with latest version of cffi (1.3.1) there are some warnings issued due lack of type delcarations.

```shell
/usr/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
/usr/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'git_merge_tree_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
```

These are issued loudly, so they are quite annoying.

**Comment by yan12125** [comment]
Seems this is fixed in becc265c787a7e039df67af4a8c62ae5230a0422. I've gotten the same warnings and they're gone after I upgraded pygit2.

**Comment by jpulec** [comment]
I'm running the latest version of pygit2 (0.23.2) and the latest version of cffi (1.3.1). It's the bump in cffi version, from 1.3.0 to 1.3.1 that causes these warnings to be raised. The release notes for v1.3.1 of cffi state:

```
Opaque enums are phased out from the cdefs: they now give a warning, instead of (possibly wrongly) being assumed equal to unsigned int. Please report if you get a reasonable use case for them.
```

I  believe that change is what is resulting in the warnings, in the header file ```pygit2/decl.h```.

Happy to provide more details if they will help.

**Comment by yan12125** [comment]
Not knowning why. I'm using cffi 1.3.1 and pygit2 0.23.2, too.

**Comment by jpulec** [comment]
For the record, I'm running Arch Linux, which was using packaged versions of both cffi (python2-cffi) and pygit2 (python2-pygit2). The arch package was recently bumped, which appears to have solved the issue, so I'm gonna close this as it seems that it was arch related.

**Comment by yan12125** [comment]
Another Arch Linux user! In fact it was due to a bug in [the package script](https://projects.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/python-pygit2&id=0606267d1e901250f5014c632ac7ec85e447f25c).
