### ISSUE TITLE
Segfault on import in virtualenv

### ISSUE THREAD

**Issue by svvac** [libgit2/pygit2#591]
While trying to install pygit2 on a virtualenv, I ran into several segfault issues. This is using python 3.5.1, which is not officially supported, but my distro (Arch) manages to provide a stock package for it so I decided to give it a shot.

I started with `libgit2` globally installed on the system and followed the install guide:

```
$ virtualenv foo/
$ cd foo/
$ source bin/activate
$ pip install pygit2
$ python -c 'import pygit2'
Segmentation fault (core dumped)
```

What I tried:
- Maybe `libgit2` and `pygit2` versions don't match: They do
- Maybe python can't locate the `libgit.so` file (even though I don't get the "Can't locate file" error): Tried to locally build `libgit2` as the install docs suggest, no luck here 
- Fiddled with `LIBGIT2` and `LD_LIBRARY_PATH` env vars: still no luck

I then tried to use the distro package for `pygit2`:

```
# pacman -S python-pygit2
$ python -c 'import pygit2; print("Success!")'
Success
```

So it works. As far as I can tell looking at the package definition files, Arch maintainers don't seem to apply any custom patches, so it looks like vanilla `pygit2` to me. I then tried using the distro package in my virtualenv:

```
$ virtualenv --system-site-packages foo/
$ cd foo/
$ source bin/activate
$ python -c 'import pygit2'
Segmentation fault (core dumped)
```

So it looks like it is somehow due to interaction with the virtualenv. While digging, I discovered python's `venv` module, which seems to offer more or less the same functionalities as `virtualenv`, so I gave it a shot. This time, both scenarios below worked (command is available as `pyvenv` on my system, but I reckon you can also use `python -m venv` to the same effect):

```
## Using local venv pygit2 install and global libgit2
$ pyvenv foo/
$ cd foo
$ source bin/activate
$ pip install pygit2
$ python -c 'import pygit2; print("Success!")'
Success!
```

```
## Using global pygit2 and global libgit2
$ pyvenv --system-site-packages foo/
$ cd foo
$ source bin/activate
$ python -c 'import pygit2; print("Success!")'
Success!
```

This might not even be directly related to pygit, so feel free to close this issue. At least there's some kind of ref to the issue if anyone runs into the same problem. Also, maybe this warrants tome kind of note in the docs

Cheers!

**Comment by webknjaz** [comment]
It's probably addressed by wheels shipped with v0.28.0

@jdavid this can be closed.
