### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by y2kbadbug** [libgit2/pygit2#595]
After going over the documentation, it seems to be lacking by a lot.  Instead of actually describing how each parts work, you guys are simply giving very brief descriptions that really don't make sense when trying to figure out.  The inconsistency of things that have changed without proper documentation seems pretty bad as well.

Example or poor documentation:
http://www.pygit2.org/recipes/git-clone-mirror.html

There is no actual explanation on what is going on here.  The actual latest version of pygit2 doesn't even seem that this example is valid anymore.

There are several examples.  Simple tasks that I have read have been added, but have literally not a single example on, like cloning with SSH.

**Comment by jdavid** [comment]
Hello, pull requests are welcomed.

**Comment by jdavid** [comment]
Closing. If you wish to contribute you are welcome.
