### ISSUE TITLE
some files are locked until python interpreter exits

### ISSUE THREAD

**Issue by topic2k** [libgit2/pygit2#596]
Hello,
i make a temporary bare repository, add a remote and fetch references. Then i want to delete the temporary folder, but it fails because of locked files. I've attached the following script to demonstrate what i mean:
    
    # coding=utf-8

    import tempfile
    import pygit2
    import shutil
    import os
    import stat
    
    
    def GetBranches(repoUrl):
        repo = pygit2.init_repository(tmpDir, bare=True, origin_url=repoUrl)
        remote = repo.remotes.create('temprepo', repoUrl)
        remote.fetch()
        refs = repo.listall_references()
        return refs[:]
    
    def DeleteDir(path):
        def remove_readonly(func, path, excinfo):
            os.chmod(path, stat.S_IWRITE)
            func(path)
        if os.path.exists(path):
            shutil.rmtree(path, ignore_errors=False, onerror=remove_readonly)
    
    
    tmpDir = tempfile.mkdtemp()
    print "temp dir:", tmpDir
    print "references:", GetBranches('https://github.com/libgit2/pygit2.git')
    DeleteDir(tmpDir)
    print "temp dir deleted"

[filelocktest.zip](https://github.com/libgit2/pygit2/files/139553/filelocktest.zip)

**Comment by carlosmn** [comment]
The repository's object db keeps a few files open (mapped into memory) so it doesn't have to keep opening and closing files whenever it needs to look up an object. But this is not tied to the python interpreter, but to the lifetime of the repository. If you force collecting the repository, those file handles will be closed.

You haven't said which files are the problem, what OS you're on or what the specific error message says, so I'm assuming you're on Windows as that is the OS where we would lock files by keeping them open. If this is not the case, the please provide that information.

**Comment by topic2k** [comment]
Sorrry for not being detailed enough. I'm on Windows10 64Bit with Python 3.5 (32bit) or Python 2.7 Stackless (32bit).

The files are in `tempdir\objects\pack\`, the filenames start with `pack-` and have the extensions `.pack` and `.idx`.

> If you force collecting the repository, those file handles will be closed.

I'm new to git/pygit2, can you explain me what do you mean by _force collecting the repository_?

**Comment by carlosmn** [comment]
>I'm new to git/pygit2, can you explain me what do you mean by force collecting the repository?

That's a python/garbage-collection thing. The repository object isn't necessarily freed immediately when you stop using it. The interpreter may decide to do it at a later time if it doesn't think there is a lot of memory pressure. `del repo` should be enough in most cases to get rid of the object. But as always with garbage-collected languages, you can only make sure by going into the language's GC structures.

**Comment by topic2k** [comment]
Ok, thank you for taken the time and the explanation.
