### ISSUE TITLE
TreeEntry doc error no attribute type

### ISSUE THREAD

**Issue by barry-scott** [libgit2/pygit2#602]
The TreeEntry is documented as having a "type" attribute.
The object does not have type as an attribute.

Am I right in thinking that filemode does everything type could?

**Comment by jdavid** [comment]
>>> import pygit2
    >>> repo = pygit2.Repository('sandboxes/pygit2')
    >>> tentry = repo.revparse_single('HEAD').tree[0]
    >>> tentry.type
    'blob'

See libgit2's documentation for ``git_tree_entry_type`` and ``git_tree_entry_filemode``

**Comment by barry-scott** [comment]
$ rpm -q -a |grep pygit
python3-pygit2-0.23.0-0.1.fc23.x86_64
$ python3
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
/usr/lib64/python3.4/site-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
/usr/lib64/python3.4/site-packages/cffi/model.py:526: UserWarning: 'git_merge_tree_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
>>> repo = pygit2.Repository('wc/git/pygit2')
>>> te = repo.revparse_single('HEAD').tree[0]
>>> te.type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_pygit2.TreeEntry' object has no attribute 'type'
>>> 

I take it that there is an old version being shipped with Fedora 23?

**Comment by jdavid** [comment]
This feature was introduced in ``0.23.1``, see the changelog https://github.com/libgit2/pygit2#0231-2015-09-26

**Comment by pypingou** [comment]
Note that pygit2 0.23.3 is in updates-testing for Fedora 23
