### ISSUE TITLE
'TarFile' object has no attribute 'peel'

### ISSUE THREAD

**Issue by netspyer** [libgit2/pygit2#608]
When I try the sample code:
```python
>> import tarfile, pygit2
>> with tarfile.open('foo.tar', 'w') as archive:
        repo = pygit2.Repsitory('.')
        repo.write_archive(archive, repo.head.target)
```
an exception raised:
**'TarFile' object has no attribute 'peel'**

indeed, tarfile didn't have the `peel` attr.

**Comment by carlosmn** [comment]
It doesn't, but it doesn't need to. You're passing the arguments the wrong way around. The first argument is the treeish, which is why it expects to be able to peel it.

**Comment by netspyer** [comment]
@carlosmn see. But anyway, the sample code posted above was from the docstring of [repository.py](https://github.com/libgit2/pygit2/blob/master/pygit2/repository.py#L765-L768), was that out of date?

**Comment by carlosmn** [comment]
Looking at blame shows it was always wrong, likely due to the order being changed after writing the docstring but before committing.
