### ISSUE TITLE
libgit2 removal of git_blob_create_fromchunks breaks pygit2

### ISSUE THREAD

**Issue by barry-scott** [libgit2/pygit2#612]
I build libgit 2 from git master and pygit2 from master.

The result is this failure:

$ LD_LIBRARY_PATH=/usr/local/lib py3 -c import\ pygit2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/pygit2-0.24.0-py3.4-linux-x86_64.egg/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
ImportError: /usr/lib64/python3.4/site-packages/pygit2-0.24.0-py3.4-linux-x86_64.egg/_pygit2.cpython-34m.so: undefined symbol: git_blob_create_fromchunks

The cause is that this commit:

commit 6669e3e83900f76721603ed8a7ad9f7435042674
Author: Carlos Martín Nieto <cmn@dwim.me>
Date:   Sun Nov 8 04:28:08 2015 +0100

    blob: remove _fromchunks()
    
    The callback mechanism makes it awkward to write data from an IO
    source; move to `_fromstream()` which lets the caller remain in control,
    in the same vein as we prefer iterators over foreach callbacks.

1. blob.h refers to the removed function.
2. pygit2 depends on it in src/repository.c:918:

**Comment by carlosmn** [comment]
pygit2 isn't meant to work against the tip of master but the releases. The swap of `_fromchunks()` to a stream is not in a released version of libgit2, so pygit2 does not need to care.

**Comment by aspiers** [comment]
I saw this too, and recompiling `libgit2` from the `v0.24.1` tag instead of `master` fixed it.
