### ISSUE TITLE
security issue: gluon.tools.Expose will follow symlinks

### ISSUE THREAD

**Issue by chenl** [libgit2/pygit2#614]
Consider `controller/default.py` with:
```
def expose_tmp_folder():
    return dict(files=Expose('/tmp'))
```
If a user can gain write access to `/tmp` and can perform `ln -s /etc /tmp/link-to-etc`, expose_tmp_folder will happily follow that link and expose `/etc` as well. 

At a minimum the `Expose.__init__(...)` should have `follow_symlink=False`.

**Comment by chenl** [comment]
A better solution (and backward compatible) will be to examine the symlink and allow it only if the target is also under `base`

**Comment by jdavid** [comment]
Hello, are you sure you posted to the right project? This is pygit2, not gluon.

**Comment by chenl** [comment]
Here is my solution, this is not in the form of a pull request, because I didn't had time for sufficient testing.

[web2py-gluon-tools-expose-security.patch.txt](https://github.com/libgit2/pygit2/files/201316/web2py-gluon-tools-expose-security.patch.txt)

**Comment by chenl** [comment]
Arg. sorry.
