### ISSUE TITLE
pygit2.Repository() crashes on Windows

### ISSUE THREAD

**Issue by sbourdeauducq** [libgit2/pygit2#624]
We are building libgit2 and pygit2 as follows:
https://github.com/m-labs/conda-recipes/blob/master/conda/libgit2/bld.bat
https://github.com/m-labs/conda-recipes/blob/master/conda/pygit2/bld.bat

When running ``pygit2.Repository("some_path")``, if the target path contains a valid Git repository, the program crashes in ``msvcr120.dll`` called by ``git2.dll``.

I cannot get a full backtrace for the moment because of the broken M$ Visual Studio DRM.

Any guesses what may be wrong?

**Comment by ethomson** [comment]
I don't know what "DRM" you're talking about, but turning debug symbols on in the libgit2 build should at least get you somewhere.

**Comment by sbourdeauducq** [comment]
When starting Visual Studio to get a backtrace, it requires that I sign in into a M$ account. Doing so is not even possible as all clicking the "sign in" button does is display "We've had a problem" with unhelpful links to the M$ website.

**Comment by carlosmn** [comment]
Does your python build agree in calling convention with the libgit2 you're buliding? You're building libgit2 with MSVC, but it seems unlikely that python would be built that way, so they won't work well together. I would expect the python Windows devkit/SDK to come with its version of mingw which you'd have to use to compile the code you want to load with it.

**Comment by sbourdeauducq** [comment]
Python is built with Visual C++ 2015.

**Comment by sbourdeauducq** [comment]
Here is the backtrace
https://cloud.githubusercontent.com/assets/54771/14917442/92e00dd0-0e0e-11e6-898f-d3d7c7fbdf51.png

**Comment by ethomson** [comment]
Unfortunately, there is really no useful information in your screenshot.  Compiling libgit2 with debugging symbols would be helpful.  That's definitely the _first_ thing to do.  But as @carlosmn mentioned, my hunch is that you're compiling libgit2 with the wrong calling conventions.  How was python built?  stdcall or cdecl?

**Comment by sbourdeauducq** [comment]
It was an ABI (but not calling convention) mismatch; libssh2, libgit2 and pygit2 were built with VC12 and Python with VC14.
