### ISSUE TITLE
diff has memory leak

### ISSUE THREAD

**Issue by mrh1997** [libgit2/pygit2#625]
running diff on two trees (no matter if Repository.diff(), Tree.diff_to_tree()) seems to have a memory leak.
My testscript walks a big repository from root to head of master and diffs every logentry to its parent.
Although the diff result is thrown away the memory footprint of the process grows and grows (according to the Windows Taskmanager).
At some point I get a MemoryError).

My system is:
- Windows 10 (64 bit)
- Python 2.7.11 (32 bit)
- pygit2 / libgit2 0.24.0

**Comment by mrh1997** [comment]
Same Issue when using libgit 0.24.1 instead of 0.24.0 or when running it on linux (32bit).

**Comment by carlosmn** [comment]
How are you performing the diff? How are you throwing away the result? Are you deleting it or letting the garbage collector decide when to delete it? Do you have some code that shows the issue?

**Comment by mrh1997** [comment]
I extracted the bug as a small script into the following Gist: https://gist.github.com/mrh1997/9925bbb8e5f7b0ab8c88189d562ad42d

I recommend to use the attached vagrantfile. Then you may be sure that you are able to reproduce it, as it creates exactly the same machine as I used for testing...

Simply run ``vagrant up`` followed by ``vagrant ssh -- reproduce-pygit2-memleak.py``

**Comment by mrh1997** [comment]
@carlosmn: succeeded in repoducing the bug? Or do you need further information?

**Comment by jdavid** [comment]
probably the same as #943 which was fixed
