### ISSUE TITLE
Equivalent of git describe --contains

### ISSUE THREAD

**Issue by rralf** [libgit2/pygit2#631]
Is there an equivalent of git describe --contains?

**Comment by goldwynr** [comment]
No. libgit2 does not provide that as yet.
https://github.com/libgit2/libgit2/blob/2a51679005285e4e5f8642dd86dc35b46de772c1/src/describe.c#L678

**Comment by rralf** [comment]
Thanks for letting me know, even after a while! Let's close this one.
