### ISSUE TITLE
revparse isn't supported

### ISSUE THREAD

**Issue by aspiers** [libgit2/pygit2#633]
AFAICS, `pygit2` only supports [`revparse_single`](http://www.pygit2.org/revparse.html?highlight=revparse#pygit2.Repository.revparse_single), not [`revparse`](https://libgit2.github.com/libgit2/#HEAD/group/revparse/git_revparse).  This means there's no convenient way to obtain a list of revisions, e.g. like it can be done with `git rev-list A..B`.  The closest I could find was [`Repository.walk`](http://www.pygit2.org/log.html?highlight=walk#pygit2.Repository.walk), but that only lets you specify a starting point, and it presumably doesn't exclude commits in the same way that `A..B` will exclude commits which are already merged into `A`.

**Comment by carlosmn** [comment]
A walk does let you specify a stopping point, but that's nowhere close to what `rev-parse` gives you.

**Comment by jdavid** [comment]
With PR #1022 `Repository.revparse(...)` and `Repository.revparse_ext(...)` have been added, released in 1.3.0

**Comment by aspiers** [comment]
Fantastic, thanks a lot!
