### ISSUE TITLE
Can't clone from HTTPS repo using Ubuntu 16.04,  libgit2 or python-git2 packaging issue?

### ISSUE THREAD

**Issue by bkcsfi** [libgit2/pygit2#644]
Creating a new issue after reviewing #573 

I am using ubuntu packaged python-git2 Version: 1.0.1+git137-gc8b8379-2.1 on ubuntu 16.04

HTTPS appears to not be supported. 

I cannot determine if this is a dependency issue or a packaging issue nor do I know if this is a git or libgit2 problem or a python-git2 issue.  I do have libssl-dev installed, also libcurl3-gnutls (used by libgit2-24)

Can someone suggest if this is something I should follow up with ubuntu packing for libgit2, git or packaging of python-git?

Thanks

```
Python 2.7.11+ (default, Apr 17 2016, 14:00:29)                           
[GCC 5.3.1 20160413] on linux2                                            
Type "help", "copyright", "credits" or "license" for more information.    
>>> import pygit2                                                         
>>> bool(pygit2.features & pygit2.GIT_FEATURE_HTTPS)                      
False                                                                     
>>> bool(pygit2.features & pygit2.GIT_FEATURE_SSH)                        
True                                                                      
```

**Comment by carlosmn** [comment]
Debian packages do not support HTTPS as libgit2 uses OpenSSL which has... issues when dealing with GPL. If you want one with HTTPS support you'll have to build it yourself.
