### ISSUE TITLE
Currently no lightweight tags can be created

### ISSUE THREAD

**Issue by mrh1997** [libgit2/pygit2#650]
```create_tag()``` does ony create annotated tags.
I found now way to create lightweight tags.

(libgit2 seems to support lightweight tags)

**Comment by carlosmn** [comment]
There is nothing to support here. Lightweight tags are references. If you want to create one, use the reference methods.

**Comment by mrh1997** [comment]
Sorry for asking again: what is the **exact** command for creating a lightweight branch.
In the chapter for references (http://www.pygit2.org/references.html) the only command for creating sth. is ```create_branch()```, which is for branches.

In fact libgit2 has a command for creating lightweight tags (```git_tag_create_lightweight```), which does not occure anywhere in the pygit2 sources...

**Comment by carlosmn** [comment]
`Repository.create_reference()`. It looks like the it's not explicitly added in the docs, for which I'm sending a PR.
