### ISSUE TITLE
Enable AppVeyor for this repository

### ISSUE THREAD

**Issue by techtonik** [libgit2/pygit2#652]
I see that `appveyor.yml` is present, but CI itself is not enabled. Somebody from project owners should register with https://ci.appveyor.com and enable testing.

This is needed to get automatic Windows wheels to install https://github.com/sdg-mit/gitless on this platform.

**Comment by jdavid** [comment]
done, https://ci.appveyor.com/project/jdavid/pygit2/branch/master

**Comment by techtonik** [comment]
Test are failing, because file needs to be closed before directory can be removed on Windows.
