### ISSUE TITLE
Upload Windows wheels to PyPI

### ISSUE THREAD

**Issue by techtonik** [libgit2/pygit2#662]
Now that wheels are generated during AppVeyor build process - https://ci.appveyor.com/project/jdavid/pygit2/branch/master/job/vv09m50t6aym6wcw/artifacts it is possible to upload them to PyPI.

This addresses #237, #563 and fixes #455, #482, #506.

So how to make this happen?

**Comment by jdavid** [comment]
Right now appveyor is configured to run the tests only for Python 3.5, first we should run the tests for all supported versions of Python: 2.7, 3.2, 3.3, 3.4 and 3.5

**Comment by fourplusone** [comment]
I made some steps towards testing on the other python versions. https://ci.appveyor.com/project/fourplusone/pygit2/build/1.0.40

- 3.4 seems to work fine
- 3.3 and below fail 3/263 Tests
- libgit2 does not support MSVC 9 while python <= 3.2 requires MSVC 9. Compiling libgit2 with MSVC10 seems to work fine, however I don't know whether there will be compatibility issues (mainly calls into stdlib should be affected)
-  on 2.7 `pip install .` fails. I don't know why

**Comment by jdavid** [comment]
Okey, lets forget about 3.2

I don't see the ``pip install .`` failure, the 2.7 build looks very much like the 3.3 builds.

**Comment by techtonik** [comment]
So, artifacts could now be downloaded from AppVeyor and uploaded to PyPI.

**Comment by jdavid** [comment]
Done, https://pypi.python.org/pypi/pygit2/0.24.2

**Comment by techtonik** [comment]
Thanks. Now I can continue with trying to get `gitless` working on Windows. =)

**Comment by techtonik** [comment]
@jdavid there are no wheels for 0.25.0. Is there any deploy script that can be fixed?

**Comment by jdavid** [comment]
Uploaded, manually (with https://pypi.python.org/pypi/twine 's help). If anybody has an idea on how to automate this...

**Comment by techtonik** [comment]
@jdavid well, https://kirbyfan64.github.io/posts/using-appveyor-to-distribute-python-wheels.html and https://www.appveyor.com/docs/deployment/ can help..

**Comment by techtonik** [comment]
`deploy_script` is the entry -https://www.appveyor.com/docs/appveyor-yml/

**Comment by embs** [comment]
@jdavid would you please upload wheels for 0.26.2? I guess automatic upload didn't work out because build is broken. 😕 

Thank you!

**Comment by embs** [comment]
Just found https://github.com/libgit2/pygit2/issues/746#issuecomment-348463498. Don't know if manual upload is still a possibility...

**Comment by jdavid** [comment]
No it's not, the build on Windows is broken. Will have to wait for 0.26.3

In requirements.txt you can use ``pygit2!=0.26.2`` to skip this release (sorry).

**Comment by embs** [comment]
Thank you for the tip! I'll try it out.
