### ISSUE TITLE
Bad credentials hangs

### ISSUE THREAD

**Issue by jjlorenzo** [libgit2/pygit2#665]
Hi, it is anything that I can do to solve the following problem: If I enter bad credentials, instead of an error message, the execution hangs in the fetch.

``` python
credentials = pygit2.UserPass('jjlorenzo', 'bad-password')
stats = git.remotes['origin'].fetch(callbacks=pygit2.RemoteCallbacks(credentials=credentials))
# the fetch call hangs, the code after the fetch never get reached
```

Trying to debug `pygit2` I found that the execution hangs on `err = C.git_remote_fetch(self._remote, arr, fetch_opts, to_bytes(message))` I mean that this function never returns the error.

Probably this is a `libgit2` problem, is this is the case, sorry.

``` sh
❯❯❯ brew info libgit2                                                                                              
libgit2: stable 0.24.2 (bottled), HEAD
C library of Git core methods that is re-entrant and linkable
https://libgit2.github.com/
/usr/local/Cellar/libgit2/0.24.2 (101 files, 1.7M) *
  Poured from bottle on 2016-10-23 at 21:22:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libgit2.rb
==> Dependencies
Build: pkg-config ✘, cmake ✘
Recommended: libssh2 ✘
==> Options
--universal
    Build a universal binary
--without-libssh2
    Build without libssh2 support
--HEAD
    Install HEAD version

❯❯❯ yolk -l |grep git2
pygit2          - 0.24.1       - active
```

I install `libgit2-0.24.1` and the problem persists.

Thanks

**Comment by jjlorenzo** [comment]
Another information, if I implement a RemoteCallback
``` python
class GitRemoteCallbacks(pygit2.RemoteCallbacks):
  def credentials(self, url, username_from_url, allowed_types):
    print 'credentials', url, username_from_url, allowed_types
    return pygit2.UserPass('jjlorenzo', 'bad-password')
```

I get infinite calls to the credentials method, probably in this place is where the code get stuck.

My solution for the moment is asking for user and password in this place instead. Thinking well, seams reasonable, but I least I was hoping that the fetch returns the authentication error and interrupt the operation, at least with the callback method I'm able to fix user input problems.

**Comment by jjlorenzo** [comment]
https://github.com/libgit2/libgit2/issues/3761#issuecomment-256623221

**Comment by chescales** [comment]
Same problem with infinite credentials call on bad password. Drove me crazy actually, as with 2FA you need to use a token instead of the password, which together made it a nightmare :)

**Comment by jdavid** [comment]
The related libgit2 issue was closed past year, things have improved since this issue was reported, per https://github.com/libgit2/libgit2/issues/3761#issuecomment-500854417

Closing. Open new issues if there's still a related problem.
