### ISSUE TITLE
Repository path should should be able to find .git in parent directories

### ISSUE THREAD

**Issue by jouvin** [libgit2/pygit2#672]
I am trying to use `pygit2` and I found that the repository path passed to the constructor should be the actual directory where `.git` resides. I am trying to write a kind of specialized Git client and this is rather expected not to be able to specify any directory inside the working copy, like for any Git command. This is possible to search the `.git` in the parents with Python functions before calling the constructor but it would be great if it was a feature of the constructor.

**Comment by tmr232** [comment]
You can use `pygit2.discover_repository`.

**Comment by jouvin** [comment]
Thanks, I was not aware of it... Sorry for missing the information in the doc...
