### ISSUE TITLE
`lookup_reference` inconsistent return with `lookup_branch`.

### ISSUE THREAD

**Issue by Parakleta** [libgit2/pygit2#681]
`lookup_branch` returns `None` if the branch cannot be found.  `lookup_reference` (and also `revparse_single`) raises a `KeyError` in the same situation.  Returning `None` is the nicer behaviour.

**Comment by tmr232** [comment]
Currently, it only returned `None` on `GIT_ENOTFOUND`. What about the other possible errors? Should it just return `None` and ignore the errors? I don't think I like this idea.

**Comment by Parakleta** [comment]
I'm only talking about the not found case and the fact that `lookup_branch` and `lookup_reference` behave differently.  Either `KeyError` or `None` for not found in both functions is preferable to them having different behaviour from each other.  Other errors than not found should be propagated and not swallowed.

**Comment by tmr232** [comment]
I agree. I think the best course is to have all errors raise exceptions. The only issue is that we will be breaking existing code. Luckily - this path will actually break the code, and not let things pass quietly.

**Comment by tmr232** [comment]
I created a pull request with a change that should sort it out, but haven't had the time to test it properly yet.

**Comment by jdavid** [comment]
I prefer to return None. I find:

    branch = repo.lookup_branch(...)
    if branch is None:
        [...]

shorter and nicer than:

    try:
        branch = repo.lookup_branch(...)
    except KeyError:
        [...]

**Comment by tmr232** [comment]
If there's nothing to do with errors - it seems like a valid solution.
I just don't like hiding the error codes if they can be of use.

Maybe an additional `repo.get_branch(...)` that is more like the `dict.get(...)`?

**Comment by jdavid** [comment]
The ideal API would be something like:

    repo.branches.get(...)

And may be too:

    repo.branches[...]      

It would be implemented in Python, something like:

    class Branches(object):
        def __init__(self, repo):
            self.repo = repo
        def get(self, ...):
            return self.repo.lookup_branch(...)

Tests and documentation should be updated to use only the higher level interface implemented in Python (``lookup_branch`` would be considered "private").

**Comment by tmr232** [comment]
What about the remove vs. local branches?
`repo.branches` for all, `repo.local_branches` for local and `repo.remote_branches` for remote?

Also, if we do this, we should probably do it for all `repo.lookup_*` functions.

**Comment by tmr232** [comment]
I added a basic implementation of a `Branches` class to my PR so that we can reason about it https://github.com/libgit2/pygit2/pull/700/files#diff-57507982bc2ad39925ca8f387e172b29R1000

Currently supports iteration, `[]` and `get()`, and the creation of new branches using `create`. I suppose we *can* make it work with a `repo.branches['new-branch-name'] = commit`, but I don't think that's too good of an idea.

**Comment by jdavid** [comment]
I would not do ``repo.local_branches`` nor ``repo.remote_branches``. But instead enable the API to filter. Maybe ``repo.branches.filter(...)`` or ``repo.branches.values(...)`` or probably better in this case ``repo.branches.local()``

Yes, there are many things in pygit2 that should be handled the same: ``repo.references``, ``repo.submodules``, ...

**Comment by tmr232** [comment]
For now - went with the `local` and `remote` options. Have a look at let me know what you think.
Implementation is sub-par, but I want to get a feel for the interface first.
