### ISSUE TITLE
init_repository crash on None input

### ISSUE THREAD

**Issue by alexmnazarenko** [libgit2/pygit2#688]
Hi! Not sure if I should post this here or in libgit2.

Caught the segfault testing my pygit2 integration.

Very simple to reproduce:
```
import pygit2
pygit2.init_repository(None)
```

Result (Ubuntu 14.04):
`Segmentation fault (core dumped)`

Debugger says that crash occurs in inside libgit2 in some strlen call. Looks like None is converted to NULL (by cffi?), which is unexpected by git_repository_init_ext.

For now I've added type check in my code, but segfaults aren't really expected in python. Mb add TypeError in python layer?

**Comment by alexmnazarenko** [comment]
Forgot to add: 

pygit2/libgit2 version 0.25.0 (latest)
python 3.4.3
gcc 5.3.0

**Comment by carlosmn** [comment]
This does sound like a pygit2 bug where it's likely converting `None` to a `NULL` pointer, but it's not something that's valid input as a repository path. It should either be failing or passing in an empty string.

**Comment by alexmnazarenko** [comment]
Maybe it can be checked on both levels:

libgit2 can return non-zero error code

but pygit2 can check argument in advance and raise nice TypeError instead of "something_wrong_on_c_level".

That's just a suggestion from personal experience.
