### ISSUE TITLE
Doing fetch with Keypair

### ISSUE THREAD

**Issue by Fritzoid** [libgit2/pygit2#689]
Hi, 

I'm trying to do a simple fetch using ssh. The repo was cloned succesfully prior to running the code in the attached file. I can't for the life of me understand why this fails with:

Traceback (most recent call last):
  File "./fetch_bug.py", line 11, in <module>
    remote.fetch(callbacks=MyCallbacks())
  File "/usr/local/lib/python3.5/dist-packages/pygit2/remote.py", line 374, in fetch
    raise callbacks._stored_exception
  File "/usr/local/lib/python3.5/dist-packages/pygit2/remote.py", line 279, in _credentials_cb
    ccred = get_credentials(credentials, url, username, allowed)
  File "/usr/local/lib/python3.5/dist-packages/pygit2/remote.py", line 456, in get_credentials
    raise TypeError("invalid credential type")
TypeError: invalid credential type

libgit2 0.25.0 was succefully built and installed with ssh support
pygit2 was successfully installed with 'pip install pygit2'  etc.

Is this a bug or am I making an error? 

[fetch_bug.py.tar.gz](https://github.com/libgit2/pygit2/files/730030/fetch_bug.py.tar.gz)

**Comment by tmr232** [comment]
@Fritzoid Can you close the issue then?

**Comment by emirot** [comment]
> Hi,
> 
> I'm trying to do a simple fetch using ssh. The repo was cloned succesfully prior to running the code in the attached file. I can't for the life of me understand why this fails with:
> 
> Traceback (most recent call last):
> File "./fetch_bug.py", line 11, in 
> remote.fetch(callbacks=MyCallbacks())
> File "/usr/local/lib/python3.5/dist-packages/pygit2/remote.py", line 374, in fetch
> raise callbacks._stored_exception
> File "/usr/local/lib/python3.5/dist-packages/pygit2/remote.py", line 279, in _credentials_cb
> ccred = get_credentials(credentials, url, username, allowed)
> File "/usr/local/lib/python3.5/dist-packages/pygit2/remote.py", line 456, in get_credentials
> raise TypeError("invalid credential type")
> TypeError: invalid credential type
> 
> libgit2 0.25.0 was succefully built and installed with ssh support
> pygit2 was successfully installed with 'pip install pygit2' etc.
> 
> Is this a bug or am I making an error?
> 
> [fetch_bug.py.tar.gz](https://github.com/libgit2/pygit2/files/730030/fetch_bug.py.tar.gz)

What was the solution?
