### ISSUE TITLE
libssh2

### ISSUE THREAD

**Issue by tmr232** [libgit2/pygit2#699]
I think it would be good to add libssh2 to the builds to provide SSH support.
On Windows it takes quite some work to get it working (no success yet on my side). Haven't tried other OSs yet.

**Comment by tmr232** [comment]
https://github.com/libgit2/libgit2/issues/3926#issuecomment-288523226 says that it should be automatically resolved soon, but I think we should have this ticket open till then.

**Comment by tmr232** [comment]
Here is the relevant pull request - https://github.com/libgit2/libgit2/pull/4036

**Comment by Takouyii** [comment]
Does pygit2 provide SSH support now on Windows ? I have installed 0.27.0 version and get error : 
GitError: unsupported URL protocol . I check the git2.dll in python Lib with DEPENDS.exe ，and can't find libssh2.dll

**Comment by webknjaz** [comment]
Fixed for manylinux1 wheels: https://github.com/libgit2/pygit2/blob/c43db44/travis/build-manylinux1-wheels.sh#L129-L151
Windows is probably still having this problem.

**Comment by jdavid** [comment]
In issue #902 I've added a todo line to include libssh2 in windows wheels. So closing this one as a duplicate.
