### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by tmr232** [libgit2/pygit2#709]
I was thinking of adding type annotations to some of the APIs to assist IDEs in parsing them and providing useful completion.

Since it currently does not exist in the code, I preferred asking before coding.
Due to supporting both Python 2 and 3, I think the way to do it is to use syntax present [here](http://mypy.readthedocs.io/en/latest/python2.html).

There are some drawbacks:
1. Adding a new dependency - the `typing` package
1. Annotation comments are not the prettiest thing

But if we only the do the required minimum, we get more clarity when using the library, and can also use `mypy` as a verification step for new code.

@jdavid what is your opinion?

**Comment by jdavid** [comment]
+1 if integration with Travis is added

**Comment by vistatest** [comment]
Typing hints for the API are sorely missed and would be great to have.
Please, add them as separate .pyi file(s) with Python 3 typing hints.

**Comment by jdavid** [comment]
We don't support Python 2 any more, so this should be easier.
The minimum required version is Python 3.5

Anyway this should be contributed (PR), or funded (sponsored).

For reference, about `.pyi` files see https://mypy.readthedocs.io/en/stable/stubs.html

**Comment by tmr232** [comment]
If Python 2 is no longer supported - any reason to use stubs and not just add annotations to the code?

**Comment by mg-christian-axelsson** [comment]
Any status update on this? Would a PR that annotate the code be accepted?

**Comment by jdavid** [comment]
Yes, but instead of 1 big PR, I'd prefer a number of smaller PRs

(Today the minimum supported version of Python is 3.7)

**Comment by jdavid** [comment]
Since this issue was opened type hints have been added to the C extension.
For further improvements please open a PR.
