### ISSUE TITLE
Support libgit2 revert functions

### ISSUE THREAD

**Issue by mark-adams** [libgit2/pygit2#710]
Currently, pygit2 does not support libgit2's revert functions

It'd be great if we could get support for `git_revert_commit` added.

https://libgit2.github.com/libgit2/#HEAD/group/revert

**Comment by mark-adams** [comment]
@jdavid I'd be happy to take this on if there's no opposition.

**Comment by jdavid** [comment]
cool, please go ahead @mark-adams

**Comment by mark-adams** [comment]
PR #711 adds `git_revert_commit` as `Repository.revert_commit()` and is ready for review.
