### ISSUE TITLE
Failed to authenticate SSH session: Waiting for USERAUTH response

### ISSUE THREAD

**Issue by white-gecko** [libgit2/pygit2#720]
I get the message `_pygit2.GitError: Failed to authenticate SSH session: Waiting for USERAUTH response` with the following script:

```
import os
import pygit2

url = "ifigit@git.informatik.uni-leipzig.de:hardwarepraktikum/hwpb.git"        # ssh public

class MyRemoteCallback (pygit2.RemoteCallbacks):
    def credentials(self, url, username_from_url, allowed_types):
        ssh = os.path.join(os.path.expanduser('~'), '.ssh')
        print(ssh)
        pubkey = os.path.join(ssh, 'id_rsa.pub')
        privkey = os.path.join(ssh, 'id_rsa')
        return pygit2.Keypair(username_from_url, pubkey, privkey, "")

repo = pygit2.clone_repository(url, "repo", callbacks=MyRemoteCallback())
```

`id_rsa` and `id_rsa.pub` are just created with `ssh-keygen` and has no password.

Does the SSH connection also ask for the known hosts?

Maybe the objective-git issue is related: https://github.com/libgit2/objective-git/issues/511

**Comment by phatblat** [comment]
That SSH error indicates that the key was rejected by the server and it fell back to asking for a password, which timed out. Make sure the server has a copy of the public key for the key pair you are using.

**Comment by white-gecko** [comment]
Thank you. I thought for public repositories with ssh authentication it is enough to just provide any valid ssh key … but sure the server still has to know it.
