### ISSUE TITLE
`repo.diff(c1, c2, flags=pygit2.GIT_DIFF_FIND_RENAMES)` reverses diff

### ISSUE THREAD

**Issue by jnareb** [libgit2/pygit2#738]
First complaint is that there is no documentation and no examples of using `flags` (not `flag` as in description of parameters) with `Repository.diff`: http://www.pygit2.org/diff.html . Therefore I am not sure if I am using the API correctly.

Second, using `flags=pygit2.GIT_DIFF_FIND_RENAMES` for some reason **reverses** diff.

Compare 
```
>>> repo = pygit2.Repository('path/to/repo')
>>> repo.diff('HEAD^', 'HEAD', flag=pygit2.GIT_DIFF_FIND_RENAMES).patch`
```
with 
```
>>> repo.diff('HEAD^', 'HEAD').patch
```

-----

pygit2.LIBGIT2_VERSION: '0.26.0'

**Comment by marcinkuzminski** [comment]
Ping, also hitting this problem. Why this is happening? It makes libgit2 diff inconsistent with git diff

**Comment by marcinkuzminski** [comment]
OK, i actually found why this happens.

the flag is intended to be used with diff_object.find_similar(flag=pygit2.GIT_DIFF_FIND_RENAMES)

because this flag has a Int Value of `1` it's equal to diff flag for reversing a diff.

**Comment by jdavid** [comment]
Thanks @marcinkuzminski , I've improved the docs a little bit (though the change will only be deployed with the next release), hope it will be enough next time.
