### ISSUE TITLE
Requesting Release

### ISSUE THREAD

**Issue by brandonio21** [libgit2/pygit2#746]
This is redundant with #703 , et al.

I'm hoping to get the patches that submitted released for `pip install`. When will the next release occur? :)

**Comment by jdavid** [comment]
Maybe tomorrow...

**Comment by jdavid** [comment]
Done, except that this time there won't be wheels, as the build is broken on Windows, see:
https://ci.appveyor.com/project/jdavid/pygit2/branch/master

Didn't catch it before.. Since the breakage comes from #744 do you mind fixing it? :wink:

**Comment by brandonio21** [comment]
It appears that #749 fixes the build errors I introduced. Looks like there are test failures introduced in #743

**Comment by brandonio21** [comment]
Going to close this since there was indeed the release that I requested...
