### ISSUE TITLE
big endian: FAIL: test_no_context_lines (test.test_patch.PatchTest)

### ISSUE THREAD

**Issue by onovy** [libgit2/pygit2#765]
Hi,

test.test_patch.PatchTest.test_no_context_lines fails on archs mips, s390x, hppa, powerpc or ppc64. I think all of them are "big endian". This bug is new in 0.26.3, because before this version test_no_context_lines test didn't exists.

```
FAIL: test_no_context_lines (test.test_patch.PatchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_patch.py", line 196, in test_no_context_lines
    self.assertEqual(context_count, 0)
AssertionError: 1 != 0
```

See: https://buildd.debian.org/status/package.php?p=python-pygit2

Thanks for fixing.

**Comment by jdavid** [comment]
Don't have a big endian system to reproduce. PRs welcome

**Comment by jdavid** [comment]
Closing this as duplicate in favour of more recent issues #812 and #965 
(I see you already handled this in Debian by skipping the test.)
