### ISSUE TITLE
pip._vendor.requests.exceptions.SSLError: certificate verify failed

### ISSUE THREAD

**Issue by arcsector** [libgit2/pygit2#788]
Hello all,

Let me just say this tool is the most promising one I've seen yet. My current issue is with python 3.6.3:

I've successfully built libgit2, but whenever I try to install pygit2 via pip3, I get this error:
```shell
pip._vendor.requests.exceptions.SSLError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443):
 Max retries exceeded with url:
 /packages/3b/0d/c11844421c7c3b9cb84c5503185bbb5ba780144fd64f5adde572bcdcdd8a/pygit2-0.27.0.tar.gz 
(Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
```

**NOTE: you may close this if you desire, as I was able to work this out by using `sudo apt install python3-pygit2`**

However, this may be something worth looking into as it will affect all flavors of Linux, and not all of them use apt. 

I would also like to note that if you do try to clone the repo and do an install that way, it fails because of the `cffi` package.

**Comment by pypingou** [comment]
The python package repository is being migration to pypi.org and this leads to sometime unexpected behavior, of which I believe this is one.
I do expect this to be punctual though.

**Comment by arcsector** [comment]
Any date on which the migration will be finished?

**Comment by pypingou** [comment]
https://status.python.org/ seems to say it's all up and running now

**Comment by arcsector** [comment]
Works perfectly fine. Closing.
