### ISSUE TITLE
Ship wheels for Linux

### ISSUE THREAD

**Issue by techtonik** [libgit2/pygit2#793]
This is a follow up to #563.

I am trying to pack `gitless` as a snap, and absence of Linux wheel makes the process really painful. It could help if https://github.com/pypa/manylinux wheels were already available.

**Comment by jdavid** [comment]
Issue #563 done and closed.

For reference @beniwohli started this, https://github.com/beniwohli/mygit2/commit/ed4aa030b

**Comment by feisuzhu** [comment]
@jdavid 

Thank you for pointing #563 out, but I can only see win32 & win_amd64 wheels, not linux ones.

**Comment by jdavid** [comment]
yes because #563 is only about windows wheels

I won't have time to work on linux wheels in the near future

**Comment by jdavid** [comment]
Don't know. For reference https://github.com/webknjaz/pygit2/commit/8222c85b895a6e754b2a42e6fa93a621b60ca01b

**Comment by webknjaz** [comment]
So basically I've made it work here: #869. But this PR doesn't yet have wheels publishing logic...

**Comment by webknjaz** [comment]
Hey @jdavid, I may have found some issues with #869 so I'll try to address that in a separate PR.

Have you tried those wheels on your machine? (after running the build script like `travis/build-all-manylinux1-wheels.sh "pygit2" "0.27"`)

**Comment by webknjaz** [comment]
@techtonik @feisuzhu @feisuzhu could you please try that out as well? I'm currently having several extra minor commits on top of that branch which I didn't push but the wheels I get segfault... I just want to verify that the merged version is fine. And I'll probably have to ensure that there's no `*.pyc` files which can confuse the interpreter...

**Comment by jdavid** [comment]
just tested, no segfault, but some tests fail with ssl related errors such as
`the SSL certificate is invalid`

**Comment by webknjaz** [comment]
Ah... I must've broken smth in my env then...

I also saw those SSL errors. I assume that it's configured to look at certain locations in fs by default but when you run in under different OS it looks to some non-existent places.

Oh and another thing is that I was getting smth like "unknown URL scheme" with `ssh://` which I didn't address as well.

Any ideas on troubleshooting that?

**Comment by webknjaz** [comment]
Oh, and segfault proof: https://travis-ci.com/webknjaz/pygit2/jobs/178301715#L3389-L3390

It will become visible after you merge #874

**Comment by webknjaz** [comment]
It looks like link to libz is broken...
```console
➜ ldd pygit2-0.27.4/pygit2/.libs/lib*
pygit2-0.27.4/pygit2/.libs/libcurl-e8503455.so.4.5.0:
ldd: warning: you do not have execution permission for `pygit2-0.27.4/pygit2/.libs/libcurl-e8503455.so.4.5.0'
        linux-vdso.so.1 (0x00007ffc110a2000)
        libz-a147dcb0.so.1.2.3 => not found
        librt.so.1 => /lib64/librt.so.1 (0x00007f15a56ba000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f15a54b6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f15a5295000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f15a4ec4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f15a5d77000)
pygit2-0.27.4/pygit2/.libs/libgit2-d5fa10de.so.0.27.8:
ldd: warning: you do not have execution permission for `pygit2-0.27.4/pygit2/.libs/libgit2-d5fa10de.so.0.27.8'
        linux-vdso.so.1 (0x00007fffe4701000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f40dd310000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f40dd0ef000)
        libcurl-e8503455.so.4.5.0 => not found
        libz-a147dcb0.so.1.2.3 => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007f40dcd1e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f40ddc54000)
pygit2-0.27.4/pygit2/.libs/libz-a147dcb0.so.1.2.3:
ldd: warning: you do not have execution permission for `pygit2-0.27.4/pygit2/.libs/libz-a147dcb0.so.1.2.3'
        linux-vdso.so.1 (0x00007ffc4fb5b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3ed126c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3ed1852000)
```

**Comment by webknjaz** [comment]
It seems to be an upstream problem: https://github.com/pypa/manylinux/issues/60

**Comment by jdavid** [comment]
It's not only libz:

```
$ ldd  ./pygit2/.libs/libgit2-fada2a44.so.0.27.8 | grep not
	libcurl-e8503455.so.4.5.0 => not found
	libz-a147dcb0.so.1.2.3 => not found
	libssh2-ff375f42.so.1.0.1 => not found
```

**Comment by webknjaz** [comment]
True, depending on how I compiled it I also saw only libcurl in the list, in some cases...

Do you know a way of embedding those into `libgit2.so`?

**Comment by webknjaz** [comment]
@jdavid so what can we do about it?
