### ISSUE TITLE
KeypairFromMemory not working (_pygit2.GitError: err -7 (no message provided))

### ISSUE THREAD

**Issue by mew1033** [libgit2/pygit2#800]
I'm follwing the git clone via ssh example here: http://www.pygit2.org/recipes/git-clone-ssh.html (Just the second half). It's working fine when my keys are stored in files, but when I try to use the public key stored in memory option, it fails. Here's what I've done:

    >>>
    >>> git_host = 'githost.com'
    >>> org = 'myorg'
    >>> repo = 'testgitpull'
    >>>
    >>> keypair = pygit2.Keypair("git", 'TESTGIT.pub', 'TESTGIT', "icanhazgit")
    >>> callbacks = pygit2.RemoteCallbacks(credentials=keypair)
    >>> r = pygit2.clone_repository("ssh://git@%s/%s/%s" % (git_host, org, repo), "testgitpull", callbacks=callbacks)
    >>>
    >>> print r
    pygit2.Repository('/home/mew1033/testgit/testgitpull/.git/')
    >>>
    >>>
    
    
    (I deleted the folder here so that it could clone again)
    
    
    >>>
    >>> with open('TESTGIT.pub', 'r') as f:
    ...     pub = f.read()
    ...
    >>> with open('TESTGIT', 'r') as f:
    ...     priv = f.read()
    ...
    >>>
    >>>
    >>> keypair = pygit2.KeypairFromMemory("git", pub, priv, "icanhazgit")
    >>> callbacks = pygit2.RemoteCallbacks(credentials=keypair)
    >>> r = pygit2.clone_repository("ssh://git@%s/%s/%s" % (git_host, org, repo), "testgitpull", callbacks=callbacks)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 263, in clone_repository
        check_error(err)
      File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
        raise GitError(message)
    _pygit2.GitError: err -7 (no message provided)
    >>>
    >>>

**Comment by kinkerl** [comment]
i have the exact same problem. however, for reasons i do not understand, this works:

```
class MyRemoteCallbacks(pygit2.RemoteCallbacks):
    def credentials(self, url, username_from_url, allowed_types):
        if allowed_types & pygit2.credentials.GIT_CREDTYPE_USERNAME:
            return pygit2.Username("git")
        elif allowed_types & pygit2.credentials.GIT_CREDTYPE_SSH_MEMORY:
             return pygit2.KeypairFromMemory("git", pub, priv, "icanhazgit")
        else:
            return None
 r = pygit2.clone_repository("ssh://git@%s/%s/%s" % (git_host, org, repo), "testgitpull", callbacks=MyRemoteCallbacks)
```

**Comment by nelsonhp** [comment]
@kinkerl THANK YOU!

I was hitting this issue as well for some time. I tried all options I could find, but had no luck with any solutions provided anywhere else. The solution provided by kinkerl (above) works on install of library with specs as:

Ubuntu 18.04
python3.6
pygit2==0.27.4
libgit2==0.27.4
libssh2-dev==0.1.8

This is a more complete example for this solution:

WARNING: This is not actual code. It has been modified to 
be less verbose and not carry object information from actual
source. This code has not been tested, and may need to be 
modified for actual use. This is just a more verbose example
of how to use the previously mentioned methods. Use at your
own risk!
```python
"""
Author: Hunter Prendergast
Based on code by: Dennis Schwertel
Date: FEB 6, 2019
License: GPLv2 (To conform to license of pygit2)
"""
from functools import partial
import pygit2

class MyRemoteCallbacks(pygit2.RemoteCallbacks):

    def __init__(self, privk=None, pubk=None, passwd=None, credentials=None, certificate=None):
        """Overloading of initialization to allow for partial object creation."""
        if credentials is not None:
            self.credentials = credentials
        if certificate is not None:
            self.certificate = certificate
        self.privk = privk
        self.pubk = pubk
        self.passwd = passwd

    def credentials(self, url, username_from_url, allowed_types):
        if allowed_types & pygit2.credentials.GIT_CREDTYPE_USERNAME:
            return pygit2.Username("git")
        elif allowed_types & pygit2.credentials.GIT_CREDTYPE_SSH_MEMORY:
            return pygit2.KeypairFromMemory("git",
                                                                    self.pubk,
                                                                    self.privk,
                                                                    self.passwd)
        else:
            return None


def callback(privk, pubk, passwd): 
    return partial(MyRemoteCallbacks, privk=privk, pubk=pubk, passwd=passwd)

def clone(url, path, privk, pubk, passwd):
    return pygit2.clone_repository(url, path, callbacks=callback(
        privk, pubk, passwd))
```
Files are read in using standard python method:
```python
with open("some_file","r") as f:
    data = f.read()
```
Newlines have not been stripped from end of file(s).

Url is taken directly from gitlab/github for ssh clone. EX:
```
git@github.com:libgit2/pygit2.git
```

Keys generated with following command:
```
ssh-keygen -t rsa -b 4096 -P <password> -C <comment> -f <path> -q -o
```
Hopefully this helps some one else who is still staring at a screen at 2:30 
in the morning.

**Comment by jdavid** [comment]
Just added a unit test proving that this works.

Had to build libssh2 1.9.0, since the tests failed with 1.8.0

Open a new bug if you still have issues, but try first with libssh2 1.9.0, older versions not supported.
