### ISSUE TITLE
Git Pull - Is this the best way?

### ISSUE THREAD

**Issue by solvingj** [libgit2/pygit2#810]
I found this snippit online. Is it the best method we have for doing the equivalent of `git pull` at the GIT CLI?

https://github.com/MichaelBoselowitz/pygit2-examples/blob/master/examples.py#L54
```
def pull(repo, remote_name='origin', branch='master'):
    for remote in repo.remotes:
        if remote.name == remote_name:
            remote.fetch()
            remote_master_id = repo.lookup_reference('refs/remotes/origin/%s' % (branch)).target
            merge_result, _ = repo.merge_analysis(remote_master_id)
            # Up to date, do nothing
            if merge_result & pygit2.GIT_MERGE_ANALYSIS_UP_TO_DATE:
                return
            # We can just fastforward
            elif merge_result & pygit2.GIT_MERGE_ANALYSIS_FASTFORWARD:
                repo.checkout_tree(repo.get(remote_master_id))
                try:
                    master_ref = repo.lookup_reference('refs/heads/%s' % (branch))
                    master_ref.set_target(remote_master_id)
                except KeyError:
                    repo.create_branch(branch, repo.get(remote_master_id))
                repo.head.set_target(remote_master_id)
            elif merge_result & pygit2.GIT_MERGE_ANALYSIS_NORMAL:
                repo.merge(remote_master_id)

                if repo.index.conflicts is not None:
                    for conflict in repo.index.conflicts:
                        print 'Conflicts found in:', conflict[0].path
                    raise AssertionError('Conflicts, ahhhhh!!')

                user = repo.default_signature
                tree = repo.index.write_tree()
                commit = repo.create_commit('HEAD',
                                            user,
                                            user,
                                            'Merge!',
                                            tree,
                                            [repo.head.target, remote_master_id])
                # We need to do this or git CLI will think we are still merging.
                repo.state_cleanup()
            else:
                raise AssertionError('Unknown merge analysis result')

```

**Comment by pypingou** [comment]
I've been running with an equivalent of this code (from the same source actually) for a while now without problem: https://pagure.io/pagure/blob/master/f/pagure/lib/repo.py#_47

**Comment by solvingj** [comment]
decided not to use this lib. closing.

**Comment by solvingj** [comment]
```
    run_command(["git", "pull"])
```

**Comment by MasterGroosha** [comment]
> 
> 
> I've been running with an equivalent of this code (from the same source actually) for a while now without problem: https://pagure.io/pagure/blob/master/f/pagure/lib/repo.py#_47

Could you please re-upload your code somewhere? pagure.io doesn't open for me

**Comment by pypingou** [comment]
On Sat, Oct 24, 2020 at 04:58:07AM -0700, Groosha wrote:
>      I've been running with an equivalent of this code (from the same source
>      actually) for a while now without problem:
>      [1]https://pagure.io/pagure/blob/master/f/pagure/lib/repo.py#_47
> 
>    Could you please re-upload your code somewhere? pagure.io doesn't open for
>    me

This is odd, it works well for me. Do you have an error?
Also the pull is on line 89 now, I should have linked to a specific commit/tree
rather than the head of the default branch.

**Comment by MasterGroosha** [comment]
@pypingou for some unknown reason, pagure sometimes doesn't work for me, but 80% of time I can access that page. However the code you provided caused me some troubles to understand. If I have local uncommited changes which conflict with unmerged commits on server, the `merge_result` value is 5 and I always drop into `elif merge_result & pygit2.GIT_MERGE_ANALYSIS_FASTFORWARD` clause, but with no conflicts shown (`print(repo.index.conflicts)` results to None)
