### ISSUE TITLE
Inconsistent index updating

### ISSUE THREAD

**Issue by dmi1** [libgit2/pygit2#813]
I've found the following very anti-intuitive behavior.

If you create a git repository, and create (but don't git add) a file and then run the following script:

```
import pygit2

r1 = pygit2.Repository(".")
r2 = pygit2.Repository(".")

#"other" in r1.index

r2.index.add("file")
r2.index.write()

print("file" in r1.index)
```

you get the (to me) surprising result that it prints out `True`.  That is, even though the file was added to r2.index, and r1.index has not been updated, r1.index knows about the file.

What is stranger is that if you uncomment the line `"other" in r1.index`, which I would not expect to have any side effects, the script now prints out `False`.

**Comment by Richard-Mathie** [comment]
I am guessing index is lazy so it doesn't actually read until you do something to it.

try also 

`r1.index.read()`

before adding the file to `r2`

**Comment by jdavid** [comment]
Exactly, @Richard-Mathie is correct

import pygit2
  
filename = 'test.txt'

```
r1 = pygit2.Repository(".")
r1.index.read()

r2 = pygit2.Repository(".")
r2.index.add(filename)
r2.index.write()

print(filename in r1.index)
```

That would be the non-lazy behaviour.
