### ISSUE TITLE
pass reference to add_worktree 

### ISSUE THREAD

**Issue by Richard-Mathie** [libgit2/pygit2#814]
`repo.add_worktree` only has arguments of name and path so it is currently not possible to create a work tree on a specific reference (existing branches, tags ect) and it just creates a new branch `name`

```python
repo.listall_branches()
>>  ['master',
     'develop',
     'foo']

worktree_dir = tempfile.mkdtemp()
os.rmdir(worktree_dir)
worktree_name = 'foo'
worktree = repo.add_worktree(worktree_name, worktree_dir)
>>  Traceback (most recent call last):

      File "<ipython-input-134-cb34d9dc7f6a>", line 4, in <module>
        worktree = repo.add_worktree(worktree_name, worktree_dir)

    ValueError: failed to write reference 'refs/heads/foo': a reference with that name already exists.
```

my current workaround is to move the reference after the fact but this will still create the unwanted branch, and may leave files in the directory.
```python
branch = repo.branches[name]
branch.set_target(repo.branches[the_branch_i_wanted].target)
# or
branch.set_target(repo.references[some reference].target)
```

**Comment by Richard-Mathie** [comment]
further more we get a segfault on doing this on a bare repo ...
```python
>>> import pygit2
>>> repo = pygit2.init_repository('./bare_repo', True)
>>> repo.list_worktrees()
    []
>>> tree =repo.TreeBuilder().write()
>>> commit_id = repo.create_commit('refs/heads/master',
         repo.default_signature, repo.default_signature, "first commit", tree, [])
>>> repo.branches.create('develop', repo[commit_id])
>>> repo.list_worktrees()
    []
>>> repo.listall_branches()
    ['develop', 'master']
```

in bash on the repo
```bash
$ cd bare_repo
$ git branch 
      develop
    * master
$ git worktree add ../versions/develop develop
Preparing ../versions/bare/develop (identifier develop)
    HEAD is now at 4532215 first commit
$ git worktree list
    /..../bare_repo              (bare)
    /..../../versions/develop  4532215 [develop]
```
back in python
```python
>>> repo.list_worktrees()
    ['develop']
>>> repo.lookup_worktree('develop')
    Segmentation fault (core dumped)
```

Any idea why?

**Comment by jdavid** [comment]
We just wrap `git_worktree_add`, so this looks more like a feature request first for libgit2, as it lacks the `commit-ish` optional parameter in `git worktree add`, see https://libgit2.org/libgit2/#HEAD/group/worktree/git_worktree_add . Maybe open an issue in libgit2?

For the segfault, will checkout later.

**Comment by jdavid** [comment]
Reproduced, I can tell you the segfault happens in the call to `git_worktree_lookup`, so it seems a libgit2 issue, cc @carlosmn

**Comment by jdavid** [comment]
This is how to prepare the repo without using pygit2:

```bash
$ git init --bare bare
$ git --git-dir=bare update-ref refs/heads/develop `echo first | git --git-dir=bare commit-tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904`
$ git --git-dir=bare worktree add versions/develop develop
$ python -c "import pygit2; pygit2.Repository('bare').lookup_worktree('develop')"
Segmentation fault (core dumped)
```

It should be simple to write a C program that shows the segfault, without pygit2 involved.

**Comment by jdavid** [comment]
Update:

1. The bug is still present in the latest version of libgit2. Wait for v0.27.6 or v0.28.0 to be released and check again

2. Apparently the feature is already provided by libgit2, but not documented, https://github.com/libgit2/libgit2/issues/4823#issuecomment-426027136 @Richard-Mathie PR?

**Comment by jdavid** [comment]
The bug has been fixed in libgit2 0.27.7

So only the feature remains to do, @Richard-Mathie PR?

**Comment by Richard-Mathie** [comment]
ill have a look
:smile:

**Comment by jdavid** [comment]
Done with PR #889
