### ISSUE TITLE
Is Object.read_raw reversible?

### ISSUE THREAD

**Issue by SirCmpwn** [libgit2/pygit2#820]
Can I get an Object back from its raw representation?

**Comment by jdavid** [comment]
If it's a blob you can try `Repository.create_blob(...)`

For other objects I don't think there's a simple way, haven't see anything in libgit2 either, @carlosmn ?

**Comment by carlosmn** [comment]
You can write any object into the repository via `Repository.write`. libgit2 does have a version that does not write the object to disk, `git_odb_hashfile` which acts like `git hash-object` without the `-w` option.

**Comment by jdavid** [comment]
Thanks @carlosmn 

We actually wrap `git_odb_hashfile` already, `pygit2.hashfile(...)` and `pygit2.hash(...)`
https://www.pygit2.org/objects.html?highlight=hashfile#pygit2.hash

Does this answer the question @SirCmpwn ?

**Comment by SirCmpwn** [comment]
If I understand correctly, that would give me the oid, but not the blob object? In that case, no.

**Comment by jdavid** [comment]
From the oid you can get the object, if you know it's in the db:

    oid = pygit2.hash(...)
    blob = repo[oid]

Or you can use `Repository.write(...)`, which will work whether the object is already in the db or not:

    oid = repo.write(...)
    blob = repo[oid]

**Comment by SirCmpwn** [comment]
Ah, okay. Thanks!
