### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by jdavid** [libgit2/pygit2#824]
I started moving the test suite to pytest:

- [x] Use pytest
- [x] Fix appveyor tests
- [x] Use `assert`
- [x] Use pytest fixtures
- [x] Flat, use functions, not classes

**Comment by LordGolias** [comment]
Why?

**Comment by dsully** [comment]
+1 - pytest allows for succinct test without a lot of boiler plate. The fixtures are also much easier to deal with than class based testing.

**Comment by jdavid** [comment]
correct, the test suite is much easier to work with using pytest

This is done.
