### ISSUE TITLE
Add git_apply

### ISSUE THREAD

**Issue by jorgecarleitao** [libgit2/pygit2#841]
`apply` has been merged to `libgit2` in [this PR](https://github.com/libgit2/libgit2/pull/4705).
This issue is about exposing it to pygit2.

One way is to support `repository.apply(diff)`, e.g.

```
with open(path, 'r') as f:
    patch = f.read()

repo.apply(pygit2.Diff.parse_diff(patch))
```

I already have a patch for this (src/repository.*) and I am in the process of adding unit tests to it.

Is this something worth and that I should continue to put efford on?

**Comment by jdavid** [comment]
yes please
(though I will only merge when there's a release of libgit2 including the new feature)

**Comment by swills** [comment]
New libgit2 is out, want to merge this now? Would be really helpful.

**Comment by jorgecarleitao** [comment]
@swills I can work on this. There is a PR in place, #843, but apparently I am doing something wrong when linking against libgit2@master. Could use some help to understand what is happening.

**Comment by jdavid** [comment]
0.28 has not been released yet, it's a RC

The failures seem unrelated to your changes, probably `pygit2/decl.h` needs to be updated for 0.28

**Comment by jdavid** [comment]
Now libgit2 0.28 has been released. Next step is for someone to update pygit2 to work with libgit2 0.28;
@carlosmn has been doing this for a long time already, don't know whether he will volunteer again.

**Comment by jdavid** [comment]
Upgraded (except for 1 failing test). Actually @mystor did the job a while back.
