### ISSUE TITLE
Depend on pygit2 that corresponds to the installed libgit2

### ISSUE THREAD

**Issue by white-gecko** [libgit2/pygit2#847]
Sorry this is not a bug report, but a request for help.

I have a project that depends on `pygit2`. In my requirements.txt I've specified the dependency as `pygit2==0.27.2` because I have libgit2 in version 0.27.x on my system. On other systems different versions of libgit2 might be installed. How can I specify the dependency to match the locally installed version? (https://www.pygit2.org/install.html#version-numbers)

Is this even possible with pip or is this a task to be done with distutils and a setup.py?

How do other users of the pygit2 do it? Could this maybe be added to the README/Wiki?

**Comment by imbuedHope** [comment]
Something like [this](https://stackoverflow.com/questions/29222269/is-there-a-way-to-have-a-conditional-requirements-txt-file-for-my-python-applica/29222444), but in place of the OS condition, scan the filesystem for which version of the `libgit2` valid `*.so` files.

**Comment by white-gecko** [comment]
Thank you very much, but this will not work on other platforms … this might be the next problem. On Stackoverflow somebody answered to build a "fat wheel" https://stackoverflow.com/questions/53781394/install-pygit2-with-pip-in-the-same-version-as-libgit2. Would it be possible for pygit2 to publish such fat wheels on pypi?

**Comment by jdavid** [comment]
There's already issue #793 about manylinux wheels, help is appreciated.

**Comment by balki** [comment]
+1 This issue makes pygit2 unusable. Any python package using pygit2, should either depend on 0.26 or 0.27. Which means it is not portable. For e.g. Ubuntu 18.04 packages 0.26 while Ubuntu18.10 does 0.27. I want to use pygit2 for this project https://gitlab.com/balki/git-log-edit project and it is blocked because I have no way to make it pip installable.

**Comment by jdavid** [comment]
Have you tried https://pypi.org/project/venvgit2/ ?

**Comment by webknjaz** [comment]
Hopefully, https://github.com/libgit2/pygit2/pull/869 will solve this issue

**Comment by webknjaz** [comment]
@balki @imbuedHope @white-gecko #876 is another thing where help is needed if someone's up to doing some C coding...

**Comment by jdavid** [comment]
0.28.0 released with manylinux wheels (work done by @webknjaz)

closing

**Comment by webknjaz** [comment]
@jdavid great, thanks!
