### ISSUE TITLE
git object equality

### ISSUE THREAD

**Issue by imbuedHope** [libgit2/pygit2#852]
I found that object equality does not work with `pygit2.Commit` objects.

Digging deeper it looks like there is no implementation of `__eq__` (going all the way back to `object`) so it falls back to `__hash__`, and `pygit2.Commit.__hash__` is just falls back to `object.__hash__`.

Which causes this to happen.

```python
python3.6.7
>>> import pygit2
>>> repo = pygit2.Repository('.')
>>> repo.head.get_object() == repo.head.get_object()
False
```

This behavior is confusing and work arounds are quite messy.

**Comment by imbuedHope** [comment]
Did some more poking around and it looks like trying to code this in CPython would fail since `Py_hash_t` is limited to a `long` and even a `short_id` of length 5 wouldn't work. To add to it, python2.7 doesn't also has a cap on the size of `int` which limits the set of `__hash__` entires.

So, basically a solution to this would probably only work for `python3` onward and would have to be monkey pactched onto `_pygit2.Object` the python code. Unless I'm missing something. Not sure if this would be worth merging.

**Comment by jdavid** [comment]
Good catch! PRs welcome.
