### ISSUE TITLE
v0.27.3 Windows wheels do not include binaries

### ISSUE THREAD

**Issue by SpaceManiac** [libgit2/pygit2#857]
Introduced in v0.27.3. v0.27.2 is fine. The missing file is `pygit2/_libgit2.cp37-win_amd64.pyd` in the wheel. Without it, the library cannot be used without a working MSVC 14 (and presumably libgit2 headers, haven't thoroughly tested) installed. Python 3.6 wheels and 32-bit wheels are also affected.

#826 seems suspect, but I don't know enough about wheel creation to be sure.

**Comment by jdavid** [comment]
This should be fixed now with the just released `0.27.4`
