### ISSUE TITLE
pyGit2 0.27.3 broken on windows

### ISSUE THREAD

**Issue by Zangdaarr** [libgit2/pygit2#863]
We have been using pygit2 0.27.2 to help manage our git repositories for a while. 
Today someone upgrade to pygit1 0.27.3 and we started to have error messages:

First is : Microsoft Visual C++ 9.0 is required. This is new, we installed it.
Second is: 'git2.h' is missing. This seems to be related to libgit2

The thing is no one in my company is going to build libgit2 in order to have pygit2 working. Especially when version 0.27.2 was working perfectly fine. We are sticking with this version for the moment, but could this please be fixed ?

**Comment by jdavid** [comment]
This is a dup of issue #857
