### ISSUE TITLE
Tree __get__ is inconsistent with __contains__

### ISSUE THREAD

**Issue by imbuedHope** [libgit2/pygit2#864]
Since #316 `Tree.__contains__()` checks subdirectories but this is at odds with `Tree.__get__()` since it does not return objects for qeries that return `True` for `Tree.__contains__()`.

This is inconsistent. `Tree.__get__()` should also return objects from subdirectories if `Tree.__contains__()` returns `True`.

**Comment by jdavid** [comment]
This is not what I see reading the code and the unit tests,
https://github.com/libgit2/pygit2/blob/master/test/test_tree.py#L74

By the way it's `tree[..]` (or `tree.__getitem__(..)`) not `tree.__get__(..)`

Do you have an example that proves otherwise?

**Comment by imbuedHope** [comment]
It looks like something else was causing the issue. I can't seem to isolate the behavior.
