### ISSUE TITLE
Add binding for git_diff_patchid

### ISSUE THREAD

**Issue by sffc** [libgit2/pygit2#877]
This function was added to libgit2 recently (v0.27.0), but I can't find a Python binding for it in pygit2.  I would like to be able to use it.

https://libgit2.org/libgit2/#HEAD/group/diff/git_diff_patchid

We would like this feature to use in ICU tooling: [ICU-20444](https://unicode-org.atlassian.net/browse/ICU-20444)

**Comment by sffc** [comment]
We would like this feature to use in ICU tooling: [ICU-20444](https://unicode-org.atlassian.net/browse/ICU-20444)

**Comment by jdavid** [comment]
Done in PR #960
