### ISSUE TITLE
SSH Auth Fails with Passphrase protected Keypair

### ISSUE THREAD

**Issue by Church-** [libgit2/pygit2#880]
So currently on Ubuntu 18.04 using:
Python Version 2.7.15rc1
Pygit2 Version 0.26.2-2
Libgit2 Version 0.26.0+dfsg.1-1.1ubuntu0.2
libssh2 Version 1.8.0-1

It's failing to auth over ssh with a keypair protected by a keyphrase, tried the keypair with a plain git clone and that succeeded as well as trying a non keyphrase protected keypair with pygit2. I get this error back:

``` GitError: Failed to authenticate SSH session: Callback returned error
 [ERROR   ] Error occurred fetching gitfs remote 'ssh://git@hack.in.backtrace.io/source/salt.git': Failed to authenticate SSH session: Callback returned error
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1703, in _fetch
     fetch_results = origin.fetch(**fetch_kwargs)
   File "/usr/lib/python2.7/dist-packages/pygit2/remote.py", line 405, in fetch
     check_error(err)
   File "/usr/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
     raise GitError(message)
GitError: Failed to authenticate SSH session: Callback returned error
```

Example failing code is here: 
```
import pygit2

class MyRemoteCallbacks(pygit2.RemoteCallbacks):

    def credentials(self, url, username_from_url, allowed_types):
        if allowed_types & pygit2.credentials.GIT_CREDTYPE_USERNAME:
            return pygit2.Username("git")
        elif allowed_types & pygit2.credentials.GIT_CREDTYPE_SSH_KEY:
            return pygit2.Keypair("git", "/etc/salt/salt_git_key.pub", "/etc/salt/salt_git_key", "testkeyTESTKEY")
        else:
            return None

def main():
    print("Cloning Salt over ssh")
    pygit2.clone_repository("ssh://git@hack.in.backtrace.io/source/salt.git", "pygit2.git",callbacks=MyRemoteCallbacks())

```

**Comment by webknjaz** [comment]
@Church- does it still fail with new wheels?

**Comment by Church-** [comment]
@webknjaz Not a clue, ended up going without a password protected key for this. I'll need to check and close it.

**Comment by m451** [comment]
> 
> 
> @Church- does it still fail with new wheels?

I can confirm that I had the same issue with pygit2 version 0.26.2 on Ubuntu with Python3. I found this issue and uninstalled libgit2 and the old `python3-pygit2` distribution for Ubuntu and then re-installed pygit2 using pip3. With the following setup I can confirm that it was working for me with and without passphrase protected keys:

- libgit2-* Not installed
- pygit2 installed using `pip3 install pygit2`, this should include the libgit2 wheels you mentiond
- Python 3.6.9
- pip3 reports pygit2 version 1.1.1 installed
