### ISSUE TITLE
Missing ability to "stash list"

### ISSUE THREAD

**Issue by kbd** [libgit2/pygit2#885]
Hi, pygit2 is missing the ability to "stash list". The [docs](https://www.pygit2.org/working-copy.html#stash) show `stash`, `stash_apply`, `stash_drop`, and `stash_pop`, but no `stash_list`. I presume it was skipped originally because [all the stash iteration methods in libgit2](https://github.com/libgit2/libgit2/blob/master/include/git2/stash.h) require callbacks, so maybe it wasn't as straightforward to implement as the others, but it'd be nice if this function could be added.

**Comment by jdavid** [comment]
This has been implemented in PR #1117 , thanks to @jorio
