### ISSUE TITLE
Version numbering scheme

### ISSUE THREAD

**Issue by jdavid** [libgit2/pygit2#890]
This is a proposal.

Right now our version number is split in 2 parts. For instance in `0.28.0` the first part is `0.28`, which identifies which major version of libgit2 it's compatible with. The last number, `.0` we increment freely, regardless of the nature of the changes involved.

The proposal is to add another number, to tell apart releases with backwards incompatible changes. So next major release would be `0.29.0.0`:

- `0.29` matches libgit2 major version number
- `.0` will increment whenever there're backwards incompatible changes
- `.0` will increment whenever there're other changes, including new features

**Comment by webknjaz** [comment]
Maybe add one more part to match semver? `0.29` base libgi2 + `0.0.0.` for major.minor.patch.
This would allow end-users to safely rely on bugfixes-only, for example.

**Comment by dsully** [comment]
+1 on SemVer compatibility.

**Comment by pypingou** [comment]
+1 for SemVer is makes it much easier on consumer.
However, this scheme is subject to changes to libgit2 itself. So would major be bumped if libgit2 was to introduce a backward incompatible change? Or would it be restricted to pygit2 backward incompatible changes?

**Comment by jdavid** [comment]
1.0.0 just released. The main change regarding version numbers is we won't follow libgit2 any more.
Not yet SemVer as we will still introduce breaking changes in minor releases, but not in micro releases any more.

More details in https://www.pygit2.org/install.html#version-numbers

I expect new features and breaking changes to be introduced as often as in the 0.x release cycle. So probably the next releases will be 1.1.0, 1.2.0, 1.3.0, etc.

Upgrading to a new major version of libgit2 will increase the minor number as well.
