### ISSUE TITLE
Cannot install pygit2

### ISSUE THREAD

**Issue by KeerthiT30** [libgit2/pygit2#896]
[ec2-user@ip-172-31-26-20 libgit2-0.25.0]$ python -c 'import pygit2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pygit2
[ec2-user@ip-172-31-26-20 libgit2-0.25.0]$ sudo ldconfig
[ec2-user@ip-172-31-26-20 libgit2-0.25.0]$ python -c 'import pygit2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pygit2

**Comment by webknjaz** [comment]
@KeerthiT30 Have you tried `pip install pygit2`? Are you using virtualenv? Are you sure you use the same Python interpreter in `pip` and `python` commands?

#worksforme

**Comment by webknjaz** [comment]
Oh and I strongly recommend you using the last version (`0.28.0` ATM) since it has binary wheels compatible with `manylinux1` which means that no compilation needed on supported platforms as those are already pre-compiled for you.

**Comment by webknjaz** [comment]
@jdavid this looks like an invalid wontfix. Maybe worth closing if the author doesn't reply with something helpful.

**Comment by jdavid** [comment]
yes, @KeerthiT30 reopen if you can provide further information, at least how did you install pygit2

But first check: https://github.com/libgit2/pygit2/issues/603#issuecomment-404011613
Probably it's all you need.
