### ISSUE TITLE
ref.log() crashes on the reflog created by Repository.references.create()

### ISSUE THREAD

**Issue by cjerdonek** [libgit2/pygit2#901]
If you create a new reference using [Repository.references.create()](https://www.pygit2.org/references.html#pygit2.repository.References.create), then an invalid (corrupt) reflog file gets created (e.g. can't be read by `ref.log()`).

This looks to be because e.g. [`Repository_create_reference_direct`](https://github.com/libgit2/pygit2/blob/c43db4402fc2cd5064c19f359685538ad8aa4f9e/src/repository.c#L1492) passes `NULL` to `git_reference_create()` as the [`log_message` argument](https://libgit2.org/libgit2/#HEAD/group/reference/git_reference_create): https://github.com/libgit2/pygit2/blob/c43db4402fc2cd5064c19f359685538ad8aa4f9e/src/repository.c#L1492

And similarly for `Repository_create_reference_symbolic`: https://github.com/libgit2/pygit2/blob/c43db4402fc2cd5064c19f359685538ad8aa4f9e/src/repository.c#L1527-L1528

**Comment by cjerdonek** [comment]
Actually, I think the issue isn't with writing, but with reading a file containing a line with no log message. `ref.log()` will crash if the log message is `NULL`: https://github.com/libgit2/pygit2/blob/c43db4402fc2cd5064c19f359685538ad8aa4f9e/src/reference.c#L66

**Comment by jdavid** [comment]
Can you provide a complete example? I cannot reproduce it.

**Comment by cjerdonek** [comment]
This is what I'm getting:

```python
ref = repo.references['refs/heads/master']
list(ref.log())  # works
ref = repo.references.create('refs/heads/foo', ref.target)
list(ref.log())  # crashes
```

**Comment by cjerdonek** [comment]
Thanks!
