### ISSUE TITLE
Why I should specify path for clone_repository?

### ISSUE THREAD

**Issue by GreatBahram** [libgit2/pygit2#904]
Hi,

First of all, thanks for your great effort on pygit2,

I was wonder why don't you create the directory based on the URL like the way `git-clone` acts? The path is a mandatory attribute in clone_repository function, but maybe it shouldn't be.

**Comment by imbuedHope** [comment]
Mostly because the underlying `libgit2` implementation does it that way, I think.

**Comment by GreatBahram** [comment]
OK
