### ISSUE TITLE
Diff when commit has multiple parents?

### ISSUE THREAD

**Issue by ronnyli** [libgit2/pygit2#907]
Hi, I hope this isn't a dumb question:

How would I call `repo.diff` if a commit has multiple parents? I found this [StackOverflow answer](https://stackoverflow.com/a/25519606/10928982) that says a commit with 2 parents is a 3-way merge. Does that mean I should call `repo.diff` twice?

Thanks for your help.

**Comment by imbuedHope** [comment]
Depends on what you want out of the diff

- If you want the changes to the branch caused by the merge, diff against the first parent.
- If you want the changes that were needed to resolve merge conflicts diff against the second parent.

**Comment by ronnyli** [comment]
ah that makes so much sense. Thank you!
