### ISSUE TITLE
Documentation poor, cannot use module

### ISSUE THREAD

**Issue by SwitchedToGitlab** [libgit2/pygit2#964]
There are too many mistakes and omissions in the docs to make this module usable, and too many for me to go through and add issues for one by one. I've been playing with this module for several days now and I still cannot reliably discover a repo and make a commit. 

I get that just sounds like a rant, but I'm actually not sure what to even suggest here. Considering that I have yet to use this module for anything useful whatsoever, I suggest that you start with some docs that actually explain how to use this thing in the real world. I personally think that, after reading most of the docs, that the module is overly complicated and difficult to use. Most of the docs make almost no sense to me, and I've been using both GIT and Python for years now. 

Some examples of what I mean:

**Example 1:**
```>>> author = Signature('Alice Author', 'alice@authors.tld')
>>> committer = Signature('Cecil Committer', 'cecil@committers.tld')
>>> tree = repo.TreeBuilder().write()
>>> repo.create_commit(
... 'refs/heads/master', # the name of the reference to update
... author, committer, 'one line commit message\n\ndetailed commit message',
... tree, # binary string representing the tree object ID
... [] # list of binary strings representing parents of the new commit
... )
'#\xe4<u\xfe\xd6\x17\xa0\xe6\xa2\x8b\xb6\xdc35$\xcf-\x8b~'
```

Does not work. I get the error: 

```
>>> import pygit2
>>> author = Signature("Bob Committer","bob@example.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Signature' is not defined
```
However you never actually document how to define a signature. Furthermore, why the complicated data type for something as simple as an author field? Why not just a string?

Also, what is '#\xe4<u\xfe\xd6\x17\xa0\xe6\xa2\x8b\xb6\xdc35$\xcf-\x8b~'? I'm guessing that the OID, which again is overly complicated to work with.

**Example 2:**
Trying to create a new repo I get the error: 

```ValueError: remote 'origin' already exists``` even though I am already handling `git.AlreadyExists` in a try/catch statement. How in the world is that even possible? Why is it throwing a different error type now??

**Example 3:**

From [the Repository docs](https://www.pygit2.org/repository.html):

```pygit2.init_repository(path, bare=False, flags=16, mode=0, workdir_path=None, description=None, template_path=None, initial_head=None, origin_url=None)```

Yet there is no '16' defined in the docs immediately below, which are: 
The flags may be a combination of:

    GIT_REPOSITORY_INIT_BARE (overriden by the bare parameter)
    GIT_REPOSITORY_INIT_NO_REINIT
    GIT_REPOSITORY_INIT_NO_DOTGIT_DIR
    GIT_REPOSITORY_INIT_MKDIR
    GIT_REPOSITORY_INIT_MKPATH (set by default)
    GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE

Yet when I attmept to use a flag, I get this: 
```>>> pygit2.init_repository('.', bare=False, flags=GIT_REPOSITORY_INIT_NO_REINIT, mode=0, workdir_path=None, description=None, template_path=None, initial_head=None, origin_url=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'GIT_REPOSITORY_INIT_NO_REINIT' is not defined
```

These are just a few examples. This module is functionally useless unless you spend the time reverse engineering this code. 

Not sure what I'm trying to accomplish with this, as I'm pretty sure it will be ignored/summarily closed, but at least I can vent for this thing wasting my time and warn others looking for a quick and simple answer to interacting with a GIT repo in Python that this is probably not the module that you're looking for.

**Comment by richo** [comment]
All the errors you've posted are because of how Python's module system works. If you `from pygit2 import *` first it should start working.

With that said, this isn't super constructive criticism which you even acknowledged before posting so I'm not sure what you're hoping to achieve here.

**Comment by SwitchedToGitlab** [comment]
> All the errors you've posted are because of how Python's module system works.

Nope, sorry.

```>>> pygit2.init_repository('.', bare=False, flags=GIT_REPOSITORY_INIT_NO_REINIT, mode=0, workdir_path=None, description=None, template_path=None, initial_head=None, origin_url=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'GIT_REPOSITORY_INIT_NO_REINIT' is not defined
```

Still errors out. How do you define flags?? No one seems to know....

>  If you from pygit2 import * first it should start working.

This is my point on the docs. You could have included that **ONE LINE**  (```from pygit2 import *``) in the ```create_repo``` example and it would have made that clear. Not once you do actually do you ```from pygit2 import *``` in your docs. I had to read the entire objects page to figure out that you for some god-awful reason you decided to make something as simple as a "committer" string have to create an object (I still do not understand the reasoning behind this). 

> isn't super constructive criticism

While I get that, I'm just trying to see if there is already a GIT repo in a directory, not trying to become a package maintainer or read 300 pages of poor module documentation. I should be able to pick up a module that does something useful within a day or two without having to step through code. It's also exceptionally frustrating when one or two lines or documentation could save you 5 hours of work, especially when it's very clear no one has actually stepped through said docs and checked them for usability. 

Software without working documentation is not working software.

**Comment by richo** [comment]
This isn't my project, I just happen to have set the watch bit at some point am trying to help. Don't shoot the messenger :)

The reason for a committer being a richer object than just a String is because pygit2 mostly defaults to being a python frontend to libgit2, which in turn models a committer as being a (name, email) pair. As it happens, if you let people set it via a string then you'd have to parse them out and probably return some fairly obtuse errors when they're not formatted correctly.

`GIT_REPOSITORY_INIT_NO_REINIT` is defined right [there](https://github.com/libgit2/pygit2/blob/master/pygit2/__init__.py#L56) way up the top of pygit2's __init__.py, so my intuition is that you either didn't import the whole namespace or that you're using an older version of pygit2.

**Comment by SwitchedToGitlab** [comment]
Yeah see this is exactly what I'm talking about. Once again the poorly formatted docs wasted my time:

The [actual docs](https://www.pygit2.org/repository.html):

pygit2.init_repository(path, bare=False, flags=16, mode=0, workdir_path=None, description=None, template_path=None, initial_head=None, origin_url=None)

    Creates a new Git repository in the given path.

    If bare is True the repository will be bare, i.e. it will not have a working copy.

    The flags may be a combination of:

        GIT_REPOSITORY_INIT_BARE (overriden by the bare parameter)
        GIT_REPOSITORY_INIT_NO_REINIT
        GIT_REPOSITORY_INIT_NO_DOTGIT_DIR
        GIT_REPOSITORY_INIT_MKDIR
        GIT_REPOSITORY_INIT_MKPATH (set by default)
        GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE

    The mode parameter may be any of GIT_REPOSITORY_SHARED_UMASK (default), GIT_REPOSITORY_SHARED_GROUP or GIT_REPOSITORY_INIT_SHARED_ALL, or a custom value.

    The workdir_path, description, template_path, initial_head and origin_url are all strings.

    See libgit2’s documentation on git_repository_init_ext for further details.

    Example (***NOTE THE IMPORT STATEMENT***):
```
    >>> from pygit2 import init_repository
    >>> repo = init_repository('test')            # Creates a non-bare repository
    >>> repo = init_repository('test', bare=True) # Creates a bare repository
```
What happens when I do the same: 
```
>>> from pygit2 import init_repository
>>> foo = init_repository('.', bare=False, flags=GIT_REPOSITORY_INIT_NO_REINIT, mode=0, workdir_path=None, description=None, template_path=None, initial_head=None, origin_url=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'GIT_REPOSITORY_INIT_NO_REINIT' is not defined
```

Like I get that this is a community effort and all that, but my God it sure seems like every module that pick up I have to repeat this process over and over and I'm super over it.

**Comment by SwitchedToGitlab** [comment]
Update: so as I continue to drill into this it's clear that without substantial effort checking to see if a repository exists, and if it does add a file to it, is too difficult to do with this module. Giving up. Best of luck and thanks for the help thus far.
