### ISSUE TITLE
pygit2 1.0 was released ahead of required libgit2 release

### ISSUE THREAD

**Issue by ddevault** [libgit2/pygit2#968]
The latest libgit2 (0.28.4) does not include the changes from libgit2/libgit2#5005, which prevents pygit2 from building on the latest libgit2 version. Not sure what the appropriate change is, either rolling back #948 or asking libgit2 to prepare a new release.

**Comment by jdavid** [comment]
No, #948 was merged _after_ the release of 1.0

Though a new release of libgit2 would be nice, otherwise we cannot make a new release.

**Comment by ddevault** [comment]
Sorry, I guess I got confused with the way the branches worked out.

And to ship a bugfix release, we could just cut a branch off of 1.0.1 and then cherry pick the bugfixes to include, and tag that. Doesn't need to be tagged from master.
