### ISSUE TITLE
Access violation accessing repo config entries

### ISSUE THREAD

**Issue by GardenTools** [libgit2/pygit2#970]
When I try to access a list of the repo config, python terminates abruptly with the message

> Process finished with exit code -1073741819 (0xC0000005)

Example code that causes the issue:

```
import pygit2
repo = pygit2.Repository(path_to_git_repo)
items = list(repo.config)
for item in items:
    print(item.name, item.value)
```
by comparison the following is fine:
```
import pygit2
repo = pygit2.Repository(path_to_git_repo)
items = repo.config
for item in items:
    print(item.name, item.value)
```
and prints out the names and values of the configuration entries would be expected.

It isn't necessary to iterate over the list to cause the problem, the following will result in the same issue
```
items = list(repo.config)
print(items[0].name, items[0].value)
```

pygit2 version: 1.0.2 
python version: 3.7.4 (64-bit)
OS version: Windows 10

---

Doing a little digging https://libgit2.org/libgit2/#HEAD/group/config/git_config_next
states "The pointers returned by this function are valid until the iterator is freed." The ConfigEntry object contains the pointer returned by git_config_next, so it seems these get freed when the iteration is complete, and the ConfigEntry elements of the list are left pointing to invalid memory.

**Comment by GardenTools** [comment]
A workaround is to access the fields of each ConfigEntry and store those whilst the config is being iterated, rather than continuing to reference Config entry after ConfigIterator.\_\_del\_\_ has been called, for example the following works:
```
    configs = {entry.name: entry.value for entry in repo.config}
    for item, val in configs.items():
        print(item, val)
```

**Comment by beamerblvd** [comment]
This is almost certainly a symptom of https://github.com/libgit2/libgit2/issues/7307. It's either a legit libgit2 bug, or pygit2 is improperly using `git_config_entry_free` with iterators when it shouldn't be. It's unclear to me because the libgit2 documentation doesn't say.
