### ISSUE TITLE
pip install pygit2 fails in macos when $MACOSX_DEPLOYMENT_TARGET is set to an earlier version

### ISSUE THREAD

**Issue by projjal** [libgit2/pygit2#972]
Hi,
I have a machine where MACOSX_DEPLOYMENT_TARGET is set to 10.11
The pip install fails when building the wheel with following error message:

Running setup.py install for pygit2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l_/yn8lr6690hs58y0n36nltfgw0000gn/T/pip-install-dfim71jk/pygit2/setup.py'"'"'; __file__='"'"'/private/var/folders/l_/yn8lr6690hs58y0n36nltfgw0000gn/T/pip-install-dfim71jk/pygit2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/l_/yn8lr6690hs58y0n36nltfgw0000gn/T/pip-record-2tohehvd/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/l_/yn8lr6690hs58y0n36nltfgw0000gn/T/pip-install-dfim71jk/pygit2/
    Complete output (55 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/config.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/index.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/credentials.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/remote.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/_build.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/refspec.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/submodule.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/utils.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/blame.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/settings.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/errors.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/_run.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/repository.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    copying pygit2/ffi.py -> build/lib.macosx-10.14-x86_64-3.7/pygit2
    creating build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/oid.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/index.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/attr.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/blame.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/pack.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/revert.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/net.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/config.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/types.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/repository.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/clone.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/submodule.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/errors.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/merge.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/graph.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/describe.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/stash.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/remote.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/strarray.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/buffer.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/diff.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/common.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/proxy.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/refspec.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/transport.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    copying pygit2/decl/checkout.h -> build/lib.macosx-10.14-x86_64-3.7/pygit2/decl
    running build_ext
    generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/pygit2._libgit2.c'
    creating build/temp.macosx-10.14-x86_64-3.7
    building '_pygit2' extension
    creating build/temp.macosx-10.14-x86_64-3.7/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/blob.c -o build/temp.macosx-10.14-x86_64-3.7/src/blob.o
    error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.11" but "10.14" during configure

Setting MACOSX_DEPLOYMENT_TARGET to current sdk version 10.14 solves this issue. But would be possible to successfully install it without changing that.
Thanks.

**Comment by jdavid** [comment]
Not a Mac user here. Hopefully someone that knows Mac will help you.

**Comment by rcoup** [comment]
@projjal my understanding is modules will end up linked to the same macOS version as that used to build your _Python distribution_. This is why [in CI](https://github.com/libgit2/pygit2/actions?query=workflow%3AmacOS+branch%3Amaster) we use Python from https://python.org (which are tagged `macosx-10.9`) instead of the Homebrew one that's bundled in the CI environment.

**Comment by jdavid** [comment]
Maybe fixed with commit a66245dcf0ae6f15747fb34a2d71436a4a4dfb2b? cf. issue #1026 
Closing, reopen if still not working.
