### ISSUE TITLE
Cannot install pygit2 on windows: git2.h missing

### ISSUE THREAD

**Issue by assuiedmilan** [libgit2/pygit2#973]
Hi,

I am having an issue installign pygit2 on a windows system. My Python version is 2.7.14

I have the following error: git2.h: No such file or directory

It seems this is related to libgit2 missing. However, I installed pygit2 several times using pip and never had to download and build libgit2, it came with pygit2.

I am missing something here ? I would like to avoid having to build libgit2

Thanks

Edit: I successfully installed with pip -install pygit2==0.28.2. But why wasn't it selecting automatically the lastest valid version ?

**Comment by MasterGroosha** [comment]
Same problem with 1.0.3 version and Python 3.8

**Comment by jdavid** [comment]
@Zangdaarr Python 2 is not supported any more, you need to select 0.28.2 since it's the latest version of pygit2 that supports Python 2

@MasterGroosha Do you still have the same issue with latest version (1.1.1)?

**Comment by Zangdaarr** [comment]
Thank you but I am using python 3.7 for this project, I will test version
1.1.1

Le sam. 7 mars 2020 à 06:00, J. David Ibáñez <notifications@github.com> a
écrit :
