### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by liborw** [libgit2/pygit2#974]
I have Segmentation fault while trying to clone a repository...

`test_pygit2.py`:
```python
import pygit2
import tempfile

def test_segfault():
    with tempfile.TemporaryDirectory() as tmpdir:
        pygit2.clone_repository('https://github.com/libgit2/pygit2.git', tmpdir)

if __name__ == '__main__':
    test_segfault()
```

```sh
> python -X faulthandler -m pytest test_pygit2.py
platform linux -- Python 3.8.1, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/...
plugins: cov-2.8.1, rerunfailures-8.0
collected 1 item

test_pygit2.py [1]    1944767 segmentation fault (core dumped)  python -X faulthandler -m pytest test_pygit2.py
```

System: ArchLinux

```sh
> pacman -Q | grep git2
libgit2 1:0.28.4-1
python-pygit2 1.0.3-1
```

**Comment by jdavid** [comment]
Just tested with the master branch (and libgit2 master) and it worked. Can you try with the master branch and libgit2 0.99?

**Comment by jdavid** [comment]
Tried again with pygit2 1.1 and it worked.

This may be a packaging issue in Arch. I see libgit2 0.99 is in the Extra repo, while pygit2 1.0.3 is in the Community repo: these versions are not compatible.

Closing. Please reopen if you can reproduce with libgit2 0.99 and pygit2 1.1.1
