### ISSUE TITLE
Build using last libgit2 0.99.0 fails

### ISSUE THREAD

**Issue by tuxmaster5000** [libgit2/pygit2#979]

**Comment by tuxmaster5000** [comment]
Fix:
-#if !(LIBGIT2_VER_MAJOR == 0 && LIBGIT2_VER_MINOR == 28)
-#error You need a compatible libgit2 version (v0.28.x)
+#if !(LIBGIT2_VER_MAJOR == 0 && LIBGIT2_VER_MINOR == 99)
+#error You need a compatible libgit2 version (v0.99.x)
 #endif

**Comment by jdavid** [comment]
This is already fixed, see commit 0328605c8
