### ISSUE TITLE
"Assertion failed" when iterating over nested tree objects

### ISSUE THREAD

**Issue by lorencarvalho** [libgit2/pygit2#985]
Hi there,

I'm not sure what exactly is causing this, but I was attempting to iterate over _all_ of the files in a given commit using the tree objects and I am hitting a seg fault:

```
>>> def iter_tree(tree):
...     for e in tree:
...         if isinstance(e, Blob):
...             yield e.name
...         elif isinstance(e, Tree):
...             yield from iter_tree(e)
...

>>> c
<_pygit2.Commit at 0x107e910c0>

>>> iter_tree(c.tree)
<generator object iter_tree at 0x109193050>

>>> list(iter_tree(c.tree))
Assertion failed: (tree), function git_tree_entry_byindex, file libgit2/src/tree.c, line 317.
Abort trap: 6
```

Not sure what could be causing this, thanks for looking!

**Comment by lorencarvalho** [comment]
Sorry for the waste of time, but I was able to work arounds this by exhausting the `Commit.tree` iterator in the body of the `iter_tree` function.

I believe the issue probably stems from the fact that _accessing_ a Blob or Tree object from a commit _creates_ the object.

**Comment by jdavid** [comment]
This is a dup of issue #980 and pr #984 
A release with the fix is in progress
