### ISSUE TITLE
pygit2 1.1.1 missing build requirements in pyproject.toml

### ISSUE THREAD

**Issue by dcecile** [libgit2/pygit2#986]
Here's the warning I get from `pip` before pygit2 1.1.1 starts trying to build from source:

```
  WARNING: Missing build requirements in pyproject.toml for pygit2 from https://files.pythonhosted.org/packages/1d/c4/e0ba65178512a724a86b39565d7f9286c16d7f8e45e2f665973065c4a495/pygit2-1.1.1.tar.gz#sha256=9255d507d5d87bf22dfd57997a78908010331fc21f9a83eca121a53f657beb3c.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
```

I don't get this warning when installing pygit 1.0.3.

I'm not sure what's needed to fix this warning, but I'm guessing it's related to either [PEP 517](https://www.python.org/dev/peps/pep-0517/) or [PEP 518](https://www.python.org/dev/peps/pep-0518/), and the new pyproject.toml file from ab92bfb2cd215317c3a6711e72110c749424bc95.

**Comment by webknjaz** [comment]
> I'm not sure what's needed to fix this warning

`build-backend = "setuptools.build_meta"`
