### ISSUE TITLE
Tests use user/system git config

### ISSUE THREAD

**Issue by rcoup** [libgit2/pygit2#989]
eg:
1. run `git config --global diff.noprefix true`
2. `pytest -v test/test_diff.py`
3. some tests fail

_Presumably_ this is a symptom of the entire test run picking up the user/system git configuration, which seems bad from a reproducibility perspective? I couldn't see anything in the docs to tweak whether pygit2 picks up environment settings.

Setting `GIT_CONFIG=/dev/null` and `GIT_CONFIG_NOSYSTEM=1` would sort it for cgit, but I don't think libgit2 picks up settings in the same way?

**Comment by jdavid** [comment]
The documentation for `git_repository_config` says:

> If a configuration file has not been set, the default config set for the repository will be returned, including global and system configurations (if they are available).

https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_config

But didn't find how to set the config to a repository.

This is probably a question a libgit2 developer could answer faster than me, ping @ethomson @carlosmn

**Comment by ethomson** [comment]
We run into the same problem - the way we handle it in libgit2 is to set the various config search paths to dummy values to avoid them reading from the global paths.

libgit2: https://github.com/libgit2/libgit2/blob/master/tests/clar_libgit2.c#L565
LibGit2Sharp: https://github.com/libgit2/libgit2sharp/blob/9d2e900ca9da729eb7b20569965fc2f46d2ab2c7/LibGit2Sharp.Tests/TestHelpers/BaseFixture.cs#L93

**Comment by ethomson** [comment]
This is something that we do before we ever init up a repository.  I think that's probably the best approach, since opening a repository could hit those configs, I think.  So if you can do it generally in the test harness, all the better.

**Comment by jdavid** [comment]
Thanks!
